BC-8404 - Move tldraw config to issolate it from server config
hpi-schul-cloud/dof_app_deploy pull request #1039
Opened 2024-11-28 10:21 UTC by SevenWaysDP

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-11-28 14:00 UTC, mamutmk5 requested changes

2024-11-28 14:00 UTC, mamutmk5 commented on ansible/group_vars/production/resources.yml
> +TLDRAW_SERVER_WORKER_MEMORY_REQUESTS,: "150Mi"
Littel bit sorting and for memory request = limit.
CPU Time kann be overbooked but memory shoud not be overbooked. 
```suggestion
TLDRAW_SERVER_CPU_LIMITS: "2000m"
TLDRAW_SERVER_CPU_REQUESTS: "100m"
TLDRAW_SERVER_MEMORY_LIMITS: "2Gi"
TLDRAW_SERVER_MEMORY_REQUESTS: "2Gi"
TLDRAW_SERVER_WORKER_CPU_LIMITS: "2000m"
TLDRAW_SERVER_WORKER_CPU_REQUESTS: "100m"
TLDRAW_SERVER_WORKER_MEMORY_LIMITS,: "2Gi"
TLDRAW_SERVER_WORKER_MEMORY_REQUESTS,: "2Gi"
```

2024-11-28 14:00 UTC, mamutmk5 commented on ansible/group_vars/reference/resources.yml
> +TLDRAW_SERVER_WORKER_MEMORY_REQUESTS,: "150Mi"
Littel bit sorting and for memory request = limit.
CPU Time kann be overbooked but memory shoud not be overbooked.
```suggestion
TLDRAW_SERVER_CPU_LIMITS: "2000m"
TLDRAW_SERVER_CPU_REQUESTS: "100m"
TLDRAW_SERVER_MEMORY_LIMITS: "2Gi"
TLDRAW_SERVER_MEMORY_REQUESTS: "2Gi"
TLDRAW_SERVER_WORKER_CPU_LIMITS: "2000m"
TLDRAW_SERVER_WORKER_CPU_REQUESTS: "100m"
TLDRAW_SERVER_WORKER_MEMORY_LIMITS,: "2Gi"
TLDRAW_SERVER_WORKER_MEMORY_REQUESTS,: "2Gi"
```

2024-11-29 09:11 UTC, mamutmk5 approved these changes

2024-11-29 09:16 UTC, bergatco approved these changes

2024-12-02 10:04 UTC, merged