Add Media License Role for Vidis Sync
hpi-schul-cloud/dof_app_deploy pull request #1043
Opened 2024-12-04 10:41 UTC by sdinkov

# Description

## Links to Tickets or other pull requests

- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5364
- https://ticketsystem.dbildungscloud.de/browse/N21-2299

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-12-06 10:57 UTC, mamutmk5 requested changes

2024-12-06 10:57 UTC, mamutmk5 commented on ansible/group_vars/develop/cfg.yml
> +SERVER_VIDIS_SYNC_CRONJOB_SCHEDULE: "{{ 5 | random(seed=NAMESPACE) }}/5 * * * *"
At the PR at the server repo you set the default to every 7 minute and at this you set it to an time point for every 5 minutes?

2024-12-06 10:57 UTC, mamutmk5 commented on ansible/group_vars/nbc/instance_cfg.yml
> +GLOBAL_ANNOUNCEMENT_TEXT: ""
Why editing this?

2024-12-06 10:57 UTC, mamutmk5 commented on ansible/playbook_rollout.yml
> +      when: WITH_MEDIA_LICENSES is defined and WITH_MEDIA_LICENSES|bool
It's not needed if the Tasks in the ansible role use the right condition.

2024-12-06 11:25 UTC, sdinkov commented on ansible/group_vars/develop/cfg.yml
> +SERVER_VIDIS_SYNC_CRONJOB_SCHEDULE: "{{ 5 | random(seed=NAMESPACE) }}/5 * * * *"
this is not the final value anyways and the one in the server seems to get overwritten by whatever is defined here, I will sync them once they know how often the job should run

2024-12-06 11:27 UTC, sdinkov commented on ansible/group_vars/nbc/instance_cfg.yml
> +GLOBAL_ANNOUNCEMENT_TEXT: ""
my formatter seems to dislike single quotes in ymls, will see to it

2024-12-13 13:46 UTC, mamutmk5 commented on ansible/group_vars/nbc/instance_cfg.yml
> +WITH_MEDIA_LICENSES: true
Why have you removed the Ansible role for media-licenses from ansible/playbook_rollout.yml ?
If you only want to have it activate or deactivate on an instance add the WITH_MEDIA_LICENSES set to true to the host var file from this instance and not to all NBC instances

2024-12-13 15:53 UTC, mamutmk5 requested changes

2024-12-13 15:53 UTC, mamutmk5 commented on ansible/group_vars/nbc/instance_cfg.yml
> +WITH_MEDIA_LICENSES: true
After you re add the ansible role to the production playbook move this lines to ansible/host_vars/nbc_host/with.yml

2025-01-06 10:50 UTC, mamutmk5 commented on ansible/playbook_rollout.yml
> +      when: WITH_MEDIA_LICENSES is defined and WITH_MEDIA_LICENSES|bool
Let us lock at one of the ansible task at the media-licenses role.
```
- name: media licenses sync CronJob ConfigMap
  when: WITH_MEDIA_LICENSES is defined and WITH_MEDIA_LICENSES|bool == true
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: "{{ NAMESPACE }}"
    template: vidis-sync-cronjob-configmap.yml.j2
    state: "{{ 'present' if WITH_MEDIA_LICENSES is defined and WITH_MEDIA_LICENSES|bool else 'absent'}}"
  tags:
    - configmap
```
as you define the `state`  for this kubernetes object at this task it is not more needed to put an conditon to the ansible role at the playbock.

2025-01-07 12:51 UTC, mamutmk5 approved these changes

2025-01-10 13:05 UTC, alweber-cap approved these changes

2025-01-13 13:18 UTC, merged