N21-2313 Improve schulconnex group provisioning runtime
hpi-schul-cloud/dof_app_deploy pull request #1058
Opened 2024-12-11 09:54 UTC by MarvinOehlerkingCap

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-12-11 14:31 UTC, alweber-cap approved these changes

2024-12-11 15:06 UTC, mamutmk5 requested changes

2024-12-11 15:06 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: "120000"
To higher with 2 Minutes. Limite are 5 Seconds

2024-12-11 15:06 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: "1000"
Too high should be 100 or less

2024-12-12 10:30 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: "120000"
my bad this timeout is for another endpoint who is banned to an additional deployment for this reason that's why the 2 minutes are okay.

2024-12-13 11:55 UTC, mamutmk5 approved these changes

2024-12-13 11:55 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: "1000"
Mh okay then 1.000 and if a POD crash it will go down to 500 at first step, of the crashing not stop it will go down to 100 Users and if this not help it must be deactivate.

2024-12-13 13:39 UTC, merged