BC-1156 add config for the reference environment of Thuringia to dof_app_deploy
hpi-schul-cloud/dof_app_deploy pull request #127
Opened 2022-02-16 14:00 UTC by BlexToGo

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-02-16 14:32 UTC, mamutmk5 requested changes
Menny configuration shoud be go from ansible/host_vars/ref-thr/cfg.yml to ansible/group_vars/thr/instance_cfg.yml

missing "SC_FEDERALSTATE: thueringen" what also shoud be go to ansible/group_vars/thr/instance_cfg.yml

2022-02-16 14:32 UTC, mamutmk5 commented on ansible/host_vars/ref-thr/cfg.yml
> +SC_CONTACT_EMAIL: schulcloud-support@thillm.de
Better place where there for the group vars for all the instances
ansible/group_vars/thr/instance_cfg.yml

2022-02-16 14:32 UTC, mamutmk5 commented on ansible/host_vars/ref-thr/cfg.yml
> +FEATURE_ES_MERLIN_ENABLED: "true"
Better place where there for the group vars for all the instances
ansible/group_vars/thr/instance_cfg.yml

2022-02-16 14:32 UTC, mamutmk5 commented on ansible/host_vars/ref-thr/cfg.yml
> +CONTENT_URI: https://content.schulcloud-thueringen.de #Edusharing
Better place where there for the group vars for all the instances
ansible/group_vars/thr/instance_cfg.yml

2022-02-16 14:32 UTC, mamutmk5 commented on ansible/host_vars/ref-thr/cfg.yml
> +CONTENT_URI: https://content.schulcloud-thueringen.de #Edusharing
the kommend at the end of the line is bad, posible it's passed to the variable

2022-02-16 14:32 UTC, mamutmk5 commented on ansible/host_vars/ref-thr/cfg.yml
> +FEATURE_TSP_ENABLED: true
Better place where there for the group vars for all the instances
ansible/group_vars/thr/instance_cfg.yml

2022-02-16 14:32 UTC, mamutmk5 commented on ansible/host_vars/ref-thr/cfg.yml
> +LEGACY_COURSE_OVERVIEW_ENABLED: "false"
Better place where there for the group vars for all the instances
ansible/group_vars/thr/instance_cfg.yml

2022-02-16 15:08 UTC, mamutmk5 requested changes

2022-02-16 15:08 UTC, mamutmk5 commented on ansible/group_vars/thr/instance_cfg.yml
> +NOT_AUTHENTICATED_REDIRECT_URL: https://test.schulportal-thueringen.de/cas/login?service=https://test.schulcloud-thueringen.de/tsp-login
Also the NOT_AUTHENTICATED_REDIRECT_URL shoud be at ansible/host_vars/ref-thr/cfg.yml

2022-02-16 15:08 UTC, mamutmk5 commented on ansible/group_vars/thr/instance_cfg.yml
> +TSP_API_BASE_URL: https://test.schulportal-thueringen.de
The URL for the TSP API is expliced instance so it shoud be at ansible/host_vars/ref-thr/cfg.yml

2022-02-17 09:15 UTC, BlexToGo commented on ansible/group_vars/thr/instance_cfg.yml
> +NOT_AUTHENTICATED_REDIRECT_URL: https://test.schulportal-thueringen.de/cas/login?service=https://test.schulcloud-thueringen.de/tsp-login
`NOT_AUTHENTICATED_REDIRECT_URL` is now moved to the host config

2022-02-17 09:15 UTC, BlexToGo commented on ansible/group_vars/thr/instance_cfg.yml
> +TSP_API_BASE_URL: https://test.schulportal-thueringen.de
`TSP_API_BASE_URL` is now moved to the host config

2022-02-17 09:22 UTC, mamutmk5 approved these changes

2022-02-17 10:05 UTC, mamutmk5 requested changes
Please reaktiveade and fix the instance at https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/.github/workflows/rollout.yml#L101-L112

2022-02-17 11:09 UTC, BlexToGo commented
> Please reaktiveade and fix the instance at https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/.github/workflows/rollout.yml#L101-L112

@mamutmk5 I have reactived the `ref-thr` snippet in the github rollout and added the three github environment secrets to it, was this what you meant by fixing it?

2022-02-17 11:58 UTC, mamutmk5 commented
> > Please reaktiveade and fix the instance at https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/.github/workflows/rollout.yml#L101-L112
> 
> @mamutmk5 I have reactived the `ref-thr` snippet in the github rollout and added the three github environment secrets to it, was this what you meant by fixing it?

the code who you add with the commit https://github.com/hpi-schul-cloud/dof_app_deploy/pull/127/commits/2f6172541036203357db707b49368be3ccfff69b

2022-02-17 13:42 UTC, mamutmk5 approved these changes
Please

2022-02-17 15:06 UTC, merged