Ops 3126 add test loadtest 01
hpi-schul-cloud/dof_app_deploy pull request #129
Opened 2022-02-18 09:10 UTC by RalfNellesCap

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-02-18 15:54 UTC, mamutmk5 requested changes

2022-02-22 07:39 UTC, RalfNellesCap commented on ansible/playbook_rollout.yml
> +      when: WITH_DATABASES is defined and WITH_DATABASES|bool
added to group_vars/all group_vars/develop/
used condition and state to rollout and remove DBs

2022-02-23 11:28 UTC, mamutmk5 requested changes

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/roles/dof_mongo/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
do not work so.
What is with with vars in the templates who are not set

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/roles/dof_mongo/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
do not work so.
What is with with vars in the templates who are not set

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/roles/dof_mongo/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
do not work so.
What is with with vars in the templates who are not set

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
do not work so.
What is with with vars in the templates who are not set

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
do not work so.
What is with with vars in the templates who are not set

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
do not work so.
What is with with vars in the templates who are not set

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
do not work so.
What is with with vars in the templates who are not set

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
do not work so.
What is with with vars in the templates who are not set

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
do not work so.
What is with with vars in the templates who are not set

2022-02-23 11:28 UTC, mamutmk5 commented on ansible/host_vars/test-loadtest-01/with.yml
> +# WITH_MONGODB??
delete this line

2022-02-24 16:01 UTC, RalfNellesCap commented on ansible/roles/dof_postgresql/tasks/main.yml
> +      state: "{{ 'present' if WITH_DATABASES else 'absent' }}"
Simon suggested to use default values instead. done

2022-03-04 09:23 UTC, mamutmk5 requested changes

2022-03-04 09:23 UTC, mamutmk5 commented on ansible/roles/dof_mongo/templates/deployment.yml.j2
> +        image: {{ MONGO_IMAGE_NAME|default("mongo", true) }}:{{ MONGO_IMAGE_TAG|default("4.2.9", true) }}
No, not default set her

2022-03-04 09:23 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/templates/configmap.yml.j2
> +  POSTGRES_USER: "{{ POSTGRES_USER|default("node", true) }}"
No, not default set her

2022-03-04 09:23 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/templates/deployment.yml.j2
> +        image: {{ POSTGRES_IMAGE_NAME|default("postgres", true) }}:{{ POSTGRES_IMAGE_TAG|default("11.9", true) }}
No, not default set her

2022-03-04 09:23 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/templates/secret.yml.j2
> +  POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD|default("postgres", true) | b64encode }}"
No, not default set her

2022-03-04 16:44 UTC, mamutmk5 submitted a review, later dismissed

2022-03-07 08:56 UTC, simoncolincap approved these changes

2022-03-07 09:09 UTC, mamutmk5 approved these changes

2022-03-07 09:09 UTC, merged