BC-1167 - add thueringen production.
hpi-schul-cloud/dof_app_deploy pull request #155
Opened 2022-03-07 08:38 UTC by mamutmk5

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-03-07 12:29 UTC, Loki-Afro approved these changes

2022-03-07 14:59 UTC, Loki-Afro requested changes

2022-03-07 14:59 UTC, Loki-Afro commented on ansible/host_vars/prod-thr/version.yml
> +ANTIVIRUS_CHECK_SERVICE_IMAGE_TAG: 2.0.3
please use 2.0.5 ;)

2022-03-10 08:18 UTC, mamutmk5 commented on ansible/host_vars/prod-thr/version.yml
> +ANTIVIRUS_CHECK_SERVICE_IMAGE_TAG: 2.0.3
done

2022-03-10 12:19 UTC, Loki-Afro approved these changes

2022-03-10 12:20 UTC, merged