OPS-3102 Added infra-schulcloud-01 and infra-schulcloud-02
hpi-schul-cloud/dof_app_deploy pull request #196
Opened 2022-03-24 09:31 UTC by simoncolincap

# Description
Added infra stage group and two instances in that group infra-schulcloud-01 and infra-schulcloud-02

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/OPS-3102

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-03-24 10:51 UTC, mamutmk5 requested changes

2022-03-24 10:51 UTC, mamutmk5 commented on .github/workflows/rollout.yml
> +  infra-schulcloud-02:
please put it behind the Approval stage approve_ref
```suggestion
  infra-schulcloud-02:
    needs:
      - approve_ref 
```

2022-03-24 10:51 UTC, mamutmk5 commented on ansible/hosts
> +
What is the differnce in the config of the group_vars between infra and test?

2022-03-24 13:38 UTC, simoncolincap commented on .github/workflows/rollout.yml
> +  infra-schulcloud-02:
The infra-schulcloud instances are for testing infrastructure and run on dedicated infra-schulcloud Kubernetes clusters, they don't need approval

2022-03-24 15:29 UTC, mamutmk5 commented on ansible/hosts
> +
Okay, the 1Password vaulte is put in as secret from the enviorment.
So what exactly are the other differences?

2022-03-25 09:01 UTC, simoncolincap commented on ansible/hosts
> +
The ansible configuration is the same at the moment

2022-03-28 09:28 UTC, mamutmk5 requested changes

2022-03-28 09:28 UTC, mamutmk5 commented on ansible/host_vars/infra.schulcloud-01/version.yml
> +SCHULCLOUD_CALENDAR_IMAGE_TAG: 27.10.0
```suggestion
SCHULCLOUD_SERVER_IMAGE_TAG: 27.10.1
SCHULCLOUD_CLIENT_IMAGE_TAG: 27.10.0
NUXT_CLIENT_IMAGE_TAG: 27.10.1
SUPERHERO_DASHBOARD_IMAGE_TAG: 27.10.1
SCHULCLOUD_CALENDAR_IMAGE_TAG: 27.10.1
```

2022-03-28 09:28 UTC, mamutmk5 commented on ansible/host_vars/infra.schulcloud-02/version.yml
> +SCHULCLOUD_CALENDAR_IMAGE_TAG: 27.10.0
```suggestion
SCHULCLOUD_SERVER_IMAGE_TAG: 27.10.1
SCHULCLOUD_CLIENT_IMAGE_TAG: 27.10.0
NUXT_CLIENT_IMAGE_TAG: 27.10.1
SUPERHERO_DASHBOARD_IMAGE_TAG: 27.10.1
SCHULCLOUD_CALENDAR_IMAGE_TAG: 27.10.1
```

2022-03-28 10:01 UTC, mamutmk5 approved these changes

2022-03-29 10:59 UTC, merged