Feature/ew 132 keycloak setup
hpi-schul-cloud/dof_app_deploy pull request #224
Opened 2022-04-12 12:25 UTC by HeftyTea

# Description

Adding ErWin IDM (Keycloak) to auto deployment (develop environment).

## Links to Tickets or other pull requests

https://ticketsystem.dbildungscloud.de/browse/EW-132

## Changes

See https://ticketsystem.dbildungscloud.de/browse/EW-132

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

See https://docs.dbildungscloud.de/display/DBH/System+Architecture

## Deployment

Dependency towards PostgresSQL - see https://ticketsystem.dbildungscloud.de/browse/EW-132

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-04-12 12:51 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +            port: {{ ERWINIDM_PORT }}
Missing the livenessProbe and startupProbe see https://github.com/hpi-schul-cloud/schulcloud-server/blob/main/ansible/roles/schulcloud-server-core/templates/deployment.yml.j2#L51-L64 as ab example

2022-04-12 12:53 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: 'https://{{ DOMAIN }}'
Undo every change " to ' in this file

2022-04-12 12:54 UTC, mamutmk5 commented on ansible/roles/erwin-idm/README.MD
> +| ERWINIDM_PREFIX     | The ErWin-IDM base url prefix           |
Missing Variables

2022-04-12 14:23 UTC, HeftyTea commented on ansible/roles/dof_postgresql/templates/configmap.yml.j2
> +    psql -v ON_ERROR_STOP=1 $POSTGRES_DB -U $POSTGRES_USER -c 'CREATE SCHEMA IF NOT EXISTS erwinidm;'
done

2022-04-12 14:23 UTC, HeftyTea commented on ansible/roles/dof_postgresql/templates/deployment.yml.j2
> +            path: init_erwinidm_schema.sh
done

2022-04-12 14:28 UTC, HeftyTea commented on ansible/roles/erwin-idm/README.MD
> +
removed the 'group_vars' link since that is incomplete.

2022-04-12 14:46 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +            port: {{ ERWINIDM_PORT }}
done

2022-04-12 14:47 UTC, HeftyTea commented on ansible/group_vars/all/config.yml
> +    value: 'https://{{ DOMAIN }}'
done

2022-04-12 15:17 UTC, HeftyTea commented on ansible/roles/erwin-idm/README.MD
> +| ERWINIDM_PREFIX     | The ErWin-IDM base url prefix           |
done

2022-04-13 06:48 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +            memory: {{ ERWINIDM_MEMORY_REQUESTS|default("1Gi", true) }}
done

2022-04-13 07:44 UTC, mamutmk5 requested changes

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: 'false'
Manuel Linter says use " please
```suggestion
    value: "false"
```

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: 'dBildungscloud'
Shoud be bound to the ansible variable NAMESPACE.
It's more individual for our instances
```suggestion
    value: "{NAMESPACE}"
```

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: 'admin-cli'
Manuel Linter says use " please
```suggestion
    value: "admin-cli"
```

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: 'TBA'
Manuel Linter says use " please
```suggestion
    value: "TBA"
```

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: 'TBA'
Manuel Linter says use " please
```suggestion
    value: "TBA"
```

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/tasks/main.yml
> +    when: WITH_DATABASES
Add missing taskt to remove the init scripts Configmap

```suggestion
    
  - name: Add or Update init scripts Configmap
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: configmap-init.yml.j2
      apply: yes
    when: WITH_DATABASES

  - name: remove init scripts Configmap
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      api_version: v1
      kind: ConfigMap
      name: postgres-configmap-init
      state: absent
    when: not WITH_DATABASES
```

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/templates/configmap-init.yml.j2
> +    CREATE SCHEMA IF NOT EXISTS erwinidm;
Pleasse add the missisg new line at the file end

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/templates/configmap.yml.j2
> +  PGDATA: /var/lib/postgresql/data/pgdata
Pleasse add the missisg new line at the file end

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/dof_postgresql/templates/deployment.yml.j2
> +            path: 01_erwinidm.sql
Pleasse add the missisg new line at the file end

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/erwin-idm/README.MD
> +This role depends on the 'dof_postgressql' role providing persistence. In 'dof_postgressql', a custom 'erwinidm' schema is created during startup. The PostgreSQL role is shared with 'schulcloud-calen
It's depends on an PostgreSQL Server who is runing.
For the development enviorment the PostgreSQL Server are deployed by the ansible role [dof_postgresql](https://github.com/hpi-schul-cloud/dof_app_deploy/tree/main/ansible/roles/dof_postgresql)

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/erwin-idm/README.MD
> +| ERWINIDM_DB_PASSWORD     | The PostgresSQL user's passsword             |
Please write PostgreSQL right and not PostgresSQL

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/secret.yml.j2
> +  KC_DB_PASSWORD: {{ item.ERWINIDM_DB_PASSWORD | b64encode }}
the **item** was something old where the config was other stored for the instances.
```suggestion
  KEYCLOAK_ADMIN: {{ ERWINIDM_ADMIN_USER | b64encode }}
  KEYCLOAK_ADMIN_PASSWORD: {{ ERWINIDM_ADMIN_PASSWORD | b64encode }}
  KC_DB_URL: {{ ERWINIDM_DB_URL | b64encode }}
  KC_DB_USERNAME: {{ ERWINIDM_DB_USER | b64encode }}
  KC_DB_PASSWORD: {{ ERWINIDM_DB_PASSWORD | b64encode }}
```

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +            port: {{ ERWINIDM_PORT }}
Missing settings for the test intervall of the redinessProbe
```suggestion
        readinessProbe:
          httpGet:
            path: /health/ready
            port: {{ ERWINIDM_PORT }}
          timeoutSeconds: 4
          failureThreshold: 3
          periodSeconds: 5
```

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +          periodSeconds: 10
The readinessProbe should be set harder than the livenessProbe.
If the readiness probe fail above his failure threshold, the container will be set as not ready and no new connections form services are going to this container.
So if the readiness probe failurethreshold is below one round of the liveness probe intervall then the container is not more in use as the first or second time the liveness probe fail.
After it the container has one or two intervals of the liveness probe time to regenerate his service.
Whit the current settings the container will kill immediately after the first time the liveness probe fail and all connections to this container will be immediately dropped.
```suggestion
        livenessProbe:
          httpGet:
            path: /health/ready
            port: {{ ERWINIDM_PORT }}
          timeoutSeconds: 4
          failureThreshold: 3
          periodSeconds: 15
```

2022-04-13 07:44 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +    type: Recreate
It's better to use the strategy RollingUpdate for this service.
If you change it plese delete this service first at the develop enviorments
```suggestion
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      #maxUnavailable: 1
```

2022-04-13 08:08 UTC, HeftyTea commented on ansible/group_vars/all/config.yml
> +    value: 'false'
done

2022-04-13 08:08 UTC, HeftyTea commented on ansible/group_vars/all/config.yml
> +    value: 'dBildungscloud'
done

2022-04-13 08:28 UTC, HeftyTea commented on ansible/group_vars/all/config.yml
> +    value: 'admin-cli'
done

2022-04-13 08:28 UTC, HeftyTea commented on ansible/group_vars/all/config.yml
> +    value: 'TBA'
done

2022-04-13 08:28 UTC, HeftyTea commented on ansible/group_vars/all/config.yml
> +    value: 'TBA'
done

2022-04-13 08:32 UTC, HeftyTea commented on ansible/roles/dof_postgresql/templates/configmap.yml.j2
> +  PGDATA: /var/lib/postgresql/data/pgdata
done

2022-04-13 08:33 UTC, HeftyTea commented on ansible/roles/dof_postgresql/templates/deployment.yml.j2
> +            path: 01_erwinidm.sql
done

2022-04-13 08:36 UTC, HeftyTea commented on ansible/roles/erwin-idm/README.MD
> +This role depends on the 'dof_postgressql' role providing persistence. In 'dof_postgressql', a custom 'erwinidm' schema is created during startup. The PostgreSQL role is shared with 'schulcloud-calen
done

2022-04-13 08:36 UTC, HeftyTea commented on ansible/roles/erwin-idm/README.MD
> +| ERWINIDM_DB_PASSWORD     | The PostgresSQL user's passsword             |
done

2022-04-13 08:37 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/secret.yml.j2
> +  KC_DB_PASSWORD: {{ item.ERWINIDM_DB_PASSWORD | b64encode }}
done

2022-04-13 08:50 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +            port: {{ ERWINIDM_PORT }}
done

2022-04-13 08:53 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +          periodSeconds: 10
done

2022-04-13 08:56 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +    type: Recreate
done

2022-04-13 10:45 UTC, mamutmk5 requested changes
Missing the remove task at ansible/roles/erwin-idm/tasks/main.yml if the service is note deployed

2022-04-13 10:45 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
All tree Configuration options are secreted and should be go to https://github.com/hpi-schul-cloud/schulcloud-server/blob/main/ansible/roles/schulcloud-server-core/templates/secret.yml.j2 and set via 1Password for our systems

2022-04-13 10:45 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/erwinidm-svc-monitor.yml.j2
> +    port: prometheus
missing the definition for this endpoint at port section for the deployed container and service

2022-04-13 11:36 UTC, HeftyTea commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
done. The 'CLIENTID' is not a secret, but a configuration parameter just like tenant or database name.

2022-04-13 11:49 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/erwinidm-svc-monitor.yml.j2
> +    port: prometheus
done

2022-04-13 11:53 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/

2022-04-13 12:37 UTC, HeftyTea commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
Agreed, thanks for the link to oauth :) I moved that into the vault as well.

2022-04-14 08:18 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +            path: /health/live
can you provide me with a link where described the path below /health ?

2022-04-14 10:36 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +            path: /health/live
@mamutmk5 Sure, here you go: https://github.com/keycloak/keycloak/blob/main/docs/guides/src/main/server/health.adoc

2022-04-20 07:07 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +            path: /health/live
@HeftyTea Please check the keycloak version who support the path /health/live and more
The officiel dokumentation says nothing about it at the moment.
If i check the link from you for the version 17.0.0 it give me an 404 
https://github.com/keycloak/keycloak/blob/17.0.0/docs/guides/src/main/server/health.adoc

2022-04-25 08:31 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
> +            path: /health/live
@mamutmk5 True, the endpoints are not documented with version '17.0'. With '18.0', Keycloak added a new feature flag which splits 'metrics' and both the 'health' and 'live' endpoints to be configurable separately (https://www.keycloak.org/2022/04/keycloak-1800-released). Hence, the documentation was 'updated', i.e. introduced ;) Nevertheless the endpoints are readily available with 17.0 already. It is a default feature that comes with underlying Quarkus (see https://quarkus.io/guides/smallrye-metrics, https://quarkus.io/guides/smallrye-health for reference).

2022-04-25 15:13 UTC, mamutmk5 requested changes

2022-04-25 15:13 UTC, mamutmk5 commented on ansible/roles/erwin-idm/tasks/main.yml
> +    name: "{{ NAMESPACE }}"-erwinidm-ingress
```suggestion
    name: "{{ NAMESPACE }}-erwinidm-ingress"
```

2022-04-26 07:21 UTC, mamutmk5 requested changes

2022-04-26 07:21 UTC, mamutmk5 commented on ansible/roles/erwin-idm/tasks/main.yml
> +    apiVersion: networking.k8s.io/v1beta1
the api_version is writen wrong
```suggestion
    api_version: networking.k8s.io/v1beta1
```

2022-04-26 07:21 UTC, mamutmk5 commented on ansible/roles/erwin-idm/tasks/main.yml
> +    apiVersion: monitoring.coreos.com/v1
the api_version is writen worng  

```suggestion
    api_version: monitoring.coreos.com/v1
```

2022-04-26 08:12 UTC, HeftyTea commented on ansible/roles/erwin-idm/tasks/main.yml
> +    apiVersion: networking.k8s.io/v1beta1
done

2022-04-26 08:12 UTC, HeftyTea commented on ansible/roles/erwin-idm/tasks/main.yml
> +    apiVersion: monitoring.coreos.com/v1
done

2022-04-26 12:41 UTC, mamutmk5 approved these changes

2022-04-26 13:27 UTC, merged