BC-1614 Refactor env-vars for student-visibility
hpi-schul-cloud/dof_app_deploy pull request #225
Opened 2022-04-14 12:24 UTC by dyedwiper

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-04-20 12:12 UTC, CeEv requested changes

2022-04-20 12:12 UTC, CeEv commented on ansible/group_vars/all/config.yml
>      server: true
Is the value for booleans not needed? Then we can also remove it on line 385. 
But if it is needed, then we should add it on this place.
If we use default values from default.schema.json and no over all default is needed, please remove the env from this file. We want to reduce additional envs if it is possible.

server/client/nuxtclient is also to manage who it is displayed.

2022-04-21 09:59 UTC, dyedwiper commented on ansible/group_vars/all/config.yml
>      server: true
I kept the defaults as they were set before. If they are unnecessary, I can remove them of course.

2022-04-27 09:50 UTC, odalys-dataport approved these changes

2022-05-02 13:11 UTC, dyedwiper commented on ansible/group_vars/all/config.yml
>      server: true
Paul said to keep the defaults in that file.

2022-05-03 07:41 UTC, CeEv approved these changes

2022-05-03 07:46 UTC, merged