EW-207 Add init job to erwinidm.
hpi-schul-cloud/dof_app_deploy pull request #242
Opened 2022-05-11 07:15 UTC by HeftyTea

# Description

Adds dBildungscloud tenant (realm) initialization to erwinidm-role.

## Links to Tickets or other pull requests

- https://ticketsystem.dbildungscloud.de/browse/EW-207

## Changes

Adds initialization job to setup dBildungscloud realm altogether with client and realm specific admin user (to be used by dBildungscloud for administrative access).

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-05-11 09:23 UTC, mamutmk5 requested changes

2022-05-11 09:23 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/init_job.yml.j2
> +    app: api
api is the wrong label for this job.
```suggestion
    app: erwinidm
```

2022-05-11 09:23 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/init_job.yml.j2
> +  template:
maybe add an label to the pod for the job
```suggestion
  template:
    metadata:
      labels:
        app: erwinidm-init
```

2022-05-11 09:23 UTC, mamutmk5 commented on ansible/roles/erwin-idm/README.MD
> +This role will setup a dBildungscloud specific realm, client, and corresponding admin user. It does not support partial updates. If the target realm already exists, all further initialization steps a
Don't mention the dBildungscloud at this part.
Write some thing like "This role will setup a instance specific realm, [....]"

2022-05-11 09:23 UTC, mamutmk5 commented on ansible/group_vars/develop/cfg.yml
> +IDENTITY_MANAGEMENT__CLIENTID: "dbc"
if it's posible for both to go to the namespace as vaule?
```suggestion
IDENTITY_MANAGEMENT__TENANT: "{NAMESPACE}"
IDENTITY_MANAGEMENT__CLIENTID: "{NAMESPACE}"
```

2022-05-11 09:23 UTC, mamutmk5 commented on ansible/roles/erwin-idm/README.MD
> +Following configuration variables are used for internal and external (dBildungscloud) purpose:
Don't mention the dBildungscloud at this part.

2022-05-11 09:23 UTC, mamutmk5 commented on ansible/roles/erwin-idm/README.MD
> +| IDENTITY_MANAGEMENT\_\_CLIENTID | The default OpenID Connect client of the dBildungscloud realm |
Don't mention the dBildungscloud at this part.

2022-05-11 09:23 UTC, mamutmk5 commented on ansible/roles/erwin-idm/README.MD
> +| IDENTITY_MANAGEMENT\_\_ADMIN_CLIENTID | dBildungscloud realm admin defined client                  |
Don't mention the dBildungscloud at this part.
And sorry that i don't see it the last time

2022-05-11 13:04 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/init_job.yml.j2
> +    app: api
Done

2022-05-11 13:05 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/init_job.yml.j2
> +  template:
Done

2022-05-11 13:08 UTC, HeftyTea commented on ansible/roles/erwin-idm/README.MD
> +This role will setup a dBildungscloud specific realm, client, and corresponding admin user. It does not support partial updates. If the target realm already exists, all further initialization steps a
Done

2022-05-11 13:16 UTC, HeftyTea commented on ansible/group_vars/develop/cfg.yml
> +IDENTITY_MANAGEMENT__CLIENTID: "dbc"
The characters supported for TENANT or CLIENTID are not well documented. The characters [a-zA-Z0-9] are OK. For instance, [+*#?] are invalid. Is NAMESPACE limited somehow? Can we assume no 'special characters' here?

2022-05-11 13:19 UTC, HeftyTea commented on ansible/roles/erwin-idm/README.MD
> +| IDENTITY_MANAGEMENT\_\_CLIENTID | The default OpenID Connect client of the dBildungscloud realm |
done

2022-05-11 13:19 UTC, HeftyTea commented on ansible/roles/erwin-idm/README.MD
> +Following configuration variables are used for internal and external (dBildungscloud) purpose:
done

2022-05-11 13:21 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/configmap-init.yml.j2
> +    curl --retry 60 --retry-all-errors --retry-delay 10 "$IDM_URL_BASE/health/live" || exit 1
That would be more then 13 hours waiting? Ain't that a bit to pessimistic ? 😄 
Maybe 15 minutes will do? Updated that to 90 retries.

2022-05-12 12:36 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/configmap-init.yml.j2
> +    curl --retry 60 --retry-all-errors --retry-delay 10 "$IDM_URL_BASE/health/live" || exit 1
Yes it's 13h but its more about wait til is up there.
That's why it's so an huge amount of time.

2022-05-12 12:48 UTC, mamutmk5 commented on ansible/group_vars/develop/cfg.yml
> +IDENTITY_MANAGEMENT__CLIENTID: "dbc"
For how the namespace are build see https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/.github/workflows/deploy.yml#L90
Alternativ you cann posible use SC_THEME for it.
https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/ansible/group_vars/default/instance_cfg.yml

2022-05-12 13:13 UTC, HeftyTea commented on ansible/group_vars/develop/cfg.yml
> +IDENTITY_MANAGEMENT__CLIENTID: "dbc"
Thanks for the hint! SC_THEME seems a good option here.

2022-05-13 08:32 UTC, HeftyTea commented on ansible/roles/erwin-idm/templates/configmap-init.yml.j2
> +    curl --retry 60 --retry-all-errors --retry-delay 10 "$IDM_URL_BASE/health/live" || exit 1
done

2022-05-16 07:13 UTC, mamutmk5 approved these changes

2022-05-16 10:39 UTC, merged