Feature/n21 98 invalidate nextcloud session
hpi-schul-cloud/dof_app_deploy pull request #260
Opened 2022-05-18 13:50 UTC by alweber-cap

# Description

Added Global Logout URI and New Hydra Env-Vars for Logout Flow

## Links to Tickets or other pull requests

https://ticketsystem.dbildungscloud.de/browse/N21-93

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-05-19 08:01 UTC, mamutmk5 requested changes

2022-05-19 08:49 UTC, alweber-cap commented on ansible/group_vars/nbc/instance_cfg.yml
> +HYDRA_LOGOUT_URI: http://hydra-svc:4444/oauth2/sessions/logout
will change it to external route found in hydra ingress

2022-05-19 09:11 UTC, MarvinOehlerkingCap approved these changes

2022-05-19 09:26 UTC, mamutmk5 commented on ansible/group_vars/nbc/instance_cfg.yml
> +HYDRA_LOGOUT_URI: "https://{{ HYDRA_DNS_PREFIX }}{{ DOMAIN }}/oauth2/sessions/logout"
Why don't you set it as default for all instances even they don't have nextcloud jet?

2022-05-19 09:36 UTC, alweber-cap commented on ansible/group_vars/nbc/instance_cfg.yml
> +HYDRA_LOGOUT_URI: "https://{{ HYDRA_DNS_PREFIX }}{{ DOMAIN }}/oauth2/sessions/logout"
The existence of this ENVVAR is also used as a featuretoggle for the oauth logout. If there is no problem with setting it as a global default (we tested it and it doesn't affect functionality) we can do that

2022-05-19 12:06 UTC, mamutmk5 commented on ansible/group_vars/nbc/instance_cfg.yml
> +HYDRA_LOGOUT_URI: "https://{{ HYDRA_DNS_PREFIX }}{{ DOMAIN }}/oauth2/sessions/logout"
Both are okay

2022-05-19 12:23 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
I struggle a bit with the name _HYDRA_LOGOUT_URI_ for me it's feel like it should be more general like _OAUTH_LOGOUT_URI_ or so

2022-05-19 13:03 UTC, Loki-Afro commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
i agree :) - is there anything speaking against it?

2022-05-20 06:46 UTC, mamutmk5 approved these changes

2022-05-20 11:30 UTC, merged