Ops 3221 send rc message on ref prod deployments
hpi-schul-cloud/dof_app_deploy pull request #276
Opened 2022-06-07 14:34 UTC by aimee-889

# Description
Send a notification about the status (succeeded/failed) of a rollout to rocketchat into the "Release" channel

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/OPS-3221

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2022-06-08 11:51 UTC, BlexToGo submitted a review, later dismissed
Test with another channel was successful

2022-06-13 11:58 UTC, BlexToGo commented on .github/workflows/host.yml
> +          channel: '#release'
Necessary renaming of the rocket chat channel is already done
> Room name changed to: release by sophie.krueger

2022-06-13 12:02 UTC, aimee-889 commented on .github/workflows/host.yml
> +          channel: '#release'
Here is only the s dropped. Actually the room name could have stayed the same. Only in the github action the channel name had to be in lower case. Nevertheless RC would push the message to the upper case channel

2022-06-13 12:10 UTC, BlexToGo requested changes
Open question if the if statement of the `Send Notification to Rocket Chat` can be simplified

2022-06-13 12:10 UTC, BlexToGo commented on .github/workflows/host.yml
> +        if: always() && (contains(inputs.host_name, 'ref')) || (contains(inputs.host_name, 'prod'))
Does the `always()` still serve any purpose? If not, I would suggest simplifying this if statement for readability to
```suggestion
        if: contains(inputs.host_name, 'ref') || contains(inputs.host_name, 'prod')
```
And was it possible to quickly test if the `contains()` expression works as expected? For example, by deploying to `infra` and `dev` while having the if statement
```
        if: contains(inputs.host_name, 'infra')
```
and checking afterwards if only a message for the `infra` environment was sent to the test rocket chat channel.

2022-06-14 10:17 UTC, BlexToGo approved these changes
Conversation about `always()` is resolved, workflow is tested, approved for merge into main

2022-06-14 12:25 UTC, merged