Revert the revert "Change the update Strategy for storage to recreate (#22)"
hpi-schul-cloud/dof_app_deploy pull request #28
Opened 2021-08-30 14:13 UTC by virgilchiriac

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-08-30 16:16 UTC, mamutmk5 reviewed
Let us wait one weak or so before we remove `JWT_WHITELIST_ACCEPT_ALL: "false"` from the config, to make sure every deployment is update to the new version of the server.

2021-09-10 09:48 UTC, Loki-Afro requested changes
its about adding `JWT_WHITELIST_ACCEPT_ALL`  to default as well, not removing

2021-09-10 09:59 UTC, virgilchiriac commented
> its about adding `JWT_WHITELIST_ACCEPT_ALL` to default as well, not removing

this flag was removed on server, and should be not existing here anymore

this PR restores a commit to remove JWT_WHITELIST_ACCEPT_ALL

original commit #23
the revert: 5b235bd (the revert was needed because it was merged too soon (before the dependent server PR).

2021-09-10 10:00 UTC, Loki-Afro approved these changes

2021-09-10 10:00 UTC, merged