added missing ingress rules
hpi-schul-cloud/dof_app_deploy pull request #30
Opened 2021-08-30 16:15 UTC by Loki-Afro

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-08-30 17:23 UTC, mamutmk5 requested changes
Rejected by potential security issues.
Please add an proof that the Server Routes are secure to open.

2021-08-30 17:23 UTC, mamutmk5 commented on ansible/roles/ingress/templates/ingress.yml.j2
> +          servicePort: {{ PORT_SERVER }}
Rejected, Route is not secure for public.
The get methode is insecure

https://github.com/hpi-schul-cloud/schulcloud-server/blob/main/src/services/ldap-config/index.js
https://github.com/hpi-schul-cloud/schulcloud-server/blob/b1e528dd5c5662f1f5c9ea14bc50d84cf2a7bf38/src/services/ldap-config/service.js#L26-L34
https://github.com/hpi-schul-cloud/schulcloud-server/blob/main/src/services/ldap-config/hooks/index.js

2021-08-30 17:23 UTC, mamutmk5 commented on ansible/roles/ingress/templates/ingress.yml.j2
> +          servicePort: {{ PORT_SERVER }}
Rejected, the implementation says there is an securety issue

https://github.com/hpi-schul-cloud/schulcloud-server/blob/main/src/services/fileStorage/proxy-service.js#L707-L721

2021-08-31 08:08 UTC, Loki-Afro commented on ansible/roles/ingress/templates/ingress.yml.j2
> +          servicePort: {{ PORT_SERVER }}
the implementation is not existent, always returns 0

2021-09-03 15:25 UTC, mamutmk5 requested changes

2021-09-03 15:25 UTC, mamutmk5 commented on ansible/roles/ingress/templates/ingress.yml.j2
> +          servicePort: {{ PORT_SERVER }}
If this Route is open it's posible for persone with Permission "SCHOOL_EDIT" to generate an query for an update or patch of an school year.
https://github.com/hpi-schul-cloud/schulcloud-server/blob/3d6ee4e6ca30c1df7be5fd101af78cb3c81202ba/src/services/school/index.js#L65-L78
https://github.com/hpi-schul-cloud/schulcloud-server/blob/3d6ee4e6ca30c1df7be5fd101af78cb3c81202ba/src/services/school/index.js#L65-L78

2021-09-03 15:27 UTC, mamutmk5 commented on ansible/roles/ingress/templates/ingress.yml.j2
> +          servicePort: {{ PORT_SERVER }}
Okay, fine for me at the moment.
But maybe the function shoud be fixed at futrue.

2021-09-06 15:01 UTC, mamutmk5 commented on ansible/roles/ingress/templates/ingress.yml.j2
> +          servicePort: {{ PORT_SERVER }}
Route Fix, is open right now

2021-09-06 15:02 UTC, mamutmk5 commented on ansible/roles/ingress/templates/ingress.yml.j2
> +          servicePort: {{ PORT_SERVER }}
hpi-schul-cloud/schulcloud-server#2958

2021-09-06 15:03 UTC, mamutmk5 submitted a review, later dismissed

2021-09-07 08:01 UTC, mamutmk5 approved these changes

2021-09-07 08:04 UTC, merged