EW-197 Enable course export on develop
hpi-schul-cloud/dof_app_deploy pull request #354
Opened 2022-10-10 11:58 UTC by HeftyTea

# Description

Add new Featureflag to toggle course export as IMSCC file

## Links to Tickets or other pull requests

https://ticketsystem.dbildungscloud.de/browse/EW-197

https://github.com/hpi-schul-cloud/nuxt-client/pull/2286
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3664

## Changes

Enable course export on develop

## Datasecurity

NA

## Deployment

NA

## New Repos, NPM pakages or vendor scripts

NA

## Screenshots of UI changes

NA

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2022-10-10 17:32 UTC, Loki-Afro requested changes
i would prefer a more meaningful variable, since this is confusing with all the course copy and share stuff we currently have

2022-10-11 06:41 UTC, HeftyTea commented
@Loki-Afro Any suggestion for the variable name? The feature will allow to export, i. e. download a course as a ZIP-like file. What naming would you suggest other then 'FEATURE_COURSE_EXPORT_ENABLED'?

2022-10-11 07:09 UTC, HeftyTea commented
> i would prefer a more meaningful variable, since this is confusing with all the course copy and share stuff we currently have

Adjusted the naming to 'FEATURE_IMSCC_COURSE_EXPORT_ENABLED' matching with https://github.com/hpi-schul-cloud/nuxt-client/pull/2286

2022-10-11 10:22 UTC, Loki-Afro approved these changes

2022-10-11 10:30 UTC, pkleybolte approved these changes

2022-10-11 10:56 UTC, merged