BC-2945: set dev ES_DOMAIN to new kubernetes edusharing dev instance
hpi-schul-cloud/dof_app_deploy pull request #427
Opened 2022-12-30 12:55 UTC by ssmid

# Description
Switch to new K8 Edu-Sharing

## Links to Tickets or other pull requests
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-2945

https://github.com/hpi-schul-cloud/schulcloud-server/pull/3810

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-03-15 09:35 UTC, virgilchiriac requested changes

2023-03-15 12:20 UTC, Loki-Afro requested changes
see comments

2023-03-21 17:47 UTC, virgilchiriac commented
is this the production K8 ES instance? Do we have staging / dev instances?

2023-03-21 19:26 UTC, dimapin commented on ansible/group_vars/all/config.yml
> +    value: "https://repository.sc-dev-edusharing.dbildungscloud.dev"
Is set to http://repository.edusharing.dbildungscloud.de/

2023-03-21 19:30 UTC, dimapin commented
> is this the production K8 ES instance? Do we have staging / dev instances?

Yes, https://repository.sc-staging-edusharing.dbildungscloud.org/edu-sharing/ and https://repository.sc-dev-edusharing.dbildungscloud.dev/edu-sharing/

2023-03-21 19:30 UTC, dimapin approved these changes

2023-03-22 10:43 UTC, Loki-Afro approved these changes

2023-03-23 10:38 UTC, Loki-Afro approved these changes

2023-03-23 10:53 UTC, merged