N21-500 migration page
hpi-schul-cloud/dof_app_deploy pull request #450
Opened 2023-01-27 09:35 UTC by MarvinOehlerkingCap

# Description
- add /migration endpoint to ingress

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-01-27 09:37 UTC, arnegns approved these changes

2023-01-27 09:37 UTC, IgorCapCoder approved these changes

2023-01-30 09:00 UTC, Loki-Afro requested changes
isn't api/v3/systems kinda insecure? could not see any check if a specific user can have a specific system, instead the user gets all and also defines the filter?

2023-02-06 09:23 UTC, Loki-Afro approved these changes

2023-02-09 08:04 UTC, merged