Brb 181 fwu routing
hpi-schul-cloud/dof_app_deploy pull request #485
Opened 2023-03-14 12:13 UTC by SteKrause

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-03-15 08:00 UTC, virgilchiriac approved these changes

2023-03-15 08:01 UTC, virgilchiriac commented
pls do not merge without the server PR (wait for approval for that one, and then merge at the same time)

2023-03-15 08:15 UTC, virgilchiriac requested changes

2023-03-15 08:15 UTC, virgilchiriac commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
what about the other configuration FWU_CONTENT__ ?

2023-03-15 09:33 UTC, SteKrause commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
The configuration for 'FWU_CONTENT__' takes place via 1Password.

2023-03-23 17:11 UTC, Loki-Afro requested changes

2023-03-23 17:11 UTC, Loki-Afro commented on ansible/group_vars/all/x_ingress.yml
> +default_ingress: "{{ default_ingress_rules | combine( additional_ingress_rules | default({})) }}"
there is already something called `group_ingress` why not use that?

2023-03-23 17:11 UTC, Loki-Afro commented on ansible/host_vars/prod-brb/cfg.yml
> +# FWU_CONTENT__S3_BUCKET: fwu-content-prod
remove commented out stuff

2023-03-23 17:11 UTC, Loki-Afro commented on ansible/host_vars/ref-brb/cfg.yml
> +# FWU_CONTENT__S3_BUCKET: fwu-content-staging
remove commented out stuff

2023-03-30 11:26 UTC, Loki-Afro approved these changes

2023-03-30 11:49 UTC, SteKrause commented on ansible/host_vars/prod-brb/cfg.yml
> +# FWU_CONTENT__S3_BUCKET: fwu-content-prod
removed comments

2023-03-30 11:49 UTC, SteKrause commented on ansible/host_vars/ref-brb/cfg.yml
> +# FWU_CONTENT__S3_BUCKET: fwu-content-staging
removed comments

2023-03-31 09:57 UTC, virgilchiriac commented on ansible/group_vars/all/config.yml
> +  FWU_CONTENT__INCOMING_REQUEST_TIMEOUT_MS:
should this not have a value prop?

2023-03-31 10:00 UTC, virgilchiriac approved these changes

2023-04-04 07:52 UTC, SteKrause commented on ansible/group_vars/all/config.yml
> +  FWU_CONTENT__INCOMING_REQUEST_TIMEOUT_MS:
There's always a default value in the server for the timeout.

2023-04-04 12:33 UTC, merged