N21-654 add grace period for nbc
hpi-schul-cloud/dof_app_deploy pull request #492
Opened 2023-03-21 11:27 UTC by IgorCapCoder

# Description
adds a grace period env var for nbc instance

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/N21-654
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4001

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-03-22 10:34 UTC, arnegns submitted a review, later dismissed
See comment

2023-03-22 11:23 UTC, IgorCapCoder commented on ansible/group_vars/nbc/instance_cfg.yml
> +MIGRATION_END_GRACE_PERIOD: "604800000"
done

2023-03-22 13:20 UTC, Loki-Afro requested changes

2023-03-23 12:38 UTC, Loki-Afro approved these changes

2023-03-23 12:46 UTC, merged