BC-570 add cachet
hpi-schul-cloud/dof_app_deploy pull request #54
Opened 2021-10-29 11:45 UTC by alriese

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-11-01 12:21 UTC, mamutmk5 requested changes
Please set for each hostgroup ( default, nbc, brb ) the env vars:
FEATURE_ALERTS_ENABLED: true
ALERT_STATUS_URL: http://cachet-svc:8000

2021-11-01 12:21 UTC, mamutmk5 commented on ansible/roles/cachet/templates/svc.yml.j2
> +      protocol: TCP
The cachet pod don't have an port 80 form external.
At our  casse it woud be handeld by an ingress. ( but not in this step )

2021-11-01 12:21 UTC, mamutmk5 commented on ansible/roles/cachet/templates/svc.yml.j2
> +    - name: cachet8000
name shoud be like  the name of the container port at the deployment in this casse it where _cachet_

2021-11-01 12:21 UTC, mamutmk5 commented on ansible/roles/cachet/templates/configmap.yml.j2
> +  SESSION_DRIVER: "file"
what else session drivers are posible?

2021-11-03 14:50 UTC, alriese commented on ansible/roles/cachet/templates/configmap.yml.j2
> +  SESSION_DRIVER: "file"
The current values are just for testing purpose. The following drivers are possible: 
**session and cache drivers**: APC(U), Array, Database, File, Memcached, Redis.
**queue drivers**: None, Synchronous, Database, Beanstalk, Amazon SQS, Redis
**mail drivers**: SMTP, Mail, Sendmail, Mailgun, Mandrill, Amazon SES, SparkPost, Log

2021-12-08 10:50 UTC, closed without merging