BC-3530 & BC-3686-Added status alert triangle to the login and home page.
hpi-schul-cloud/dof_app_deploy pull request #552
Opened 2023-06-28 15:33 UTC by sszafGCA

# Description

## Links to Tickets or other pull requests
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3198
- https://ticketsystem.dbildungscloud.de/browse/BC-3530
- https://ticketsystem.dbildungscloud.de/browse/BC-3686

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-06-29 08:33 UTC, Loki-Afro commented on ansible/group_vars/nbc/instance_cfg.yml
> +FEATURE_SHOW_ALERTS_ON_HOMEPAGE: "true"
didn't you say earlier that this should only be enabled for dbc or was it really this way around?

2023-06-29 09:00 UTC, sszafGCA commented on ansible/group_vars/nbc/instance_cfg.yml
> +FEATURE_SHOW_ALERTS_ON_HOMEPAGE: "true"
no it should be disabled for dbc and enabled for brb and nbc

2023-06-29 12:13 UTC, Loki-Afro approved these changes

2023-07-03 13:37 UTC, virgilchiriac requested changes

2023-07-03 13:37 UTC, virgilchiriac commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
I think it makes more sense to have here the default value
value: "true"

2023-07-03 13:37 UTC, virgilchiriac commented on ansible/group_vars/default/instance_cfg.yml
> +FEATURE_SHOW_ALERTS_ON_HOMEPAGE: "false"
why setting it to false? ticket does not say anything about that

2023-07-03 13:37 UTC, virgilchiriac commented on ansible/group_vars/thr/instance_cfg.yml
> +FEATURE_SHOW_ALERTS_ON_HOMEPAGE: "false"
this is a bit redundant...Because normally, the home page on TSC  is actually redirecting to TSP

also, if default is false, there would be no need to overwrite the value again here

2023-07-03 13:39 UTC, virgilchiriac requested changes

2023-07-03 13:39 UTC, virgilchiriac commented on ansible/group_vars/brb/instance_cfg.yml
> +FEATURE_SHOW_ALERTS_ON_HOMEPAGE: "true"
if setting default to true, then no need to overwrite it here

2023-07-04 11:51 UTC, sszafGCA commented on ansible/group_vars/default/instance_cfg.yml
> +FEATURE_SHOW_ALERTS_ON_HOMEPAGE: "false"
because this shouldn't be displayed on dbc homepage

2023-07-06 09:14 UTC, sszafGCA commented on ansible/group_vars/all/config.yml
> +    nuxtclient: false
done

2023-07-06 09:14 UTC, sszafGCA commented on ansible/group_vars/brb/instance_cfg.yml
> +FEATURE_SHOW_ALERTS_ON_HOMEPAGE: "true"
done

2023-07-06 09:18 UTC, virgilchiriac approved these changes

2023-07-06 16:37 UTC, merged