BC-4245 - specify kubernetes resource limits for 5 k8s entities
hpi-schul-cloud/dof_app_deploy pull request #557
Opened 2023-07-05 11:31 UTC by MartinSchuhmacher

# Description
specify resource limits for ...

* api-init
* default-backend-404
* fixup-rocketchat-job
* hydra-migrate
* mongodb-query-exporter

## Links to Tickets or other pull requests
BC-4245

## Deployment

* new resource request and limit values for different tasks

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-07-05 13:09 UTC, Loki-Afro submitted a review, later dismissed

2023-07-05 13:09 UTC, Loki-Afro commented on ansible/roles/hydra/templates/job.yml.j2
> +            cpu: {{ API_CPU_LIMITS|default("200m", true) }}
why api when this is hydra?

2023-07-05 13:09 UTC, Loki-Afro commented on ansible/roles/ingress/templates/default-backend-404-deployment.yml.j2
> +            cpu: {{ API_CPU_LIMITS|default("200m", true) }}
why api when this is nginx?

2023-07-05 13:09 UTC, Loki-Afro commented on ansible/roles/rocketchat/templates/fixup-job.yml.j2
> +                cpu: {{ API_CPU_LIMITS|default("300m", true) }}
why api when this is just a script?

2023-07-05 18:38 UTC, MartinSchuhmacher commented on ansible/roles/ingress/templates/default-backend-404-deployment.yml.j2
> +            cpu: {{ API_CPU_LIMITS|default("200m", true) }}
which other env would fit here? there is only `ETHERPA_NGINX_CPU_LIMITS` and so on, but that does not seem to fit naming wise

2023-07-06 10:43 UTC, Loki-Afro commented on ansible/roles/ingress/templates/default-backend-404-deployment.yml.j2
> +            cpu: {{ API_CPU_LIMITS|default("200m", true) }}
just hardcode something for that one would be okay i think

2023-07-06 11:13 UTC, mamutmk5 commented on ansible/roles/ingress/templates/default-backend-404-deployment.yml.j2
> +            cpu: {{ API_CPU_LIMITS|default("200m", true) }}
I'm opsied to hardcode this. Create an new var for it and set an default.
Why not hardcode it, for prod we have set the limit and request for memory to the same value. 
For the dev environment there is a range between request and limit for memory.

2023-07-06 11:19 UTC, mamutmk5 commented on ansible/roles/hydra/templates/job.yml.j2
> +            cpu: {{ HYDRA_CPU_MIN|default("100m", true) }}
Short hint, don't set the CPU Time Limit for an job to less then One Core.
The value for CPU is like 1/1000 second.
A value from 200 mean that the job get 200ms cpu time from one Core at a second.
If the limit is set to 1000 it's mean that the job cann ocupie an cpu core copleat at a second for each second.

2023-07-06 11:26 UTC, MartinSchuhmacher commented on ansible/roles/hydra/templates/job.yml.j2
> +            cpu: {{ HYDRA_CPU_MIN|default("100m", true) }}
thx for the explanation 👍  will adjust here

2023-07-06 11:33 UTC, Loki-Afro commented on ansible/roles/ingress/templates/default-backend-404-deployment.yml.j2
> +            cpu: {{ API_CPU_LIMITS|default("200m", true) }}
even though it is unlikely to change during my time of existence on this very earth, do what you want :D

2023-07-07 07:19 UTC, mamutmk5 requested changes

2023-07-07 07:19 UTC, mamutmk5 commented on ansible/roles/mongodb_query_exporter/defaults/main.yaml
> +      memory: 30Mi
For the developer enviorment it's fine to set the memory Limit and request to an different values for an Deployment.
For production and referenc systems the memory limit and request shoud be the same., so an config variable for it where be greate. End thing about a littel extra memory for more querys to run, like 128Mi of memory or so for Production.

2023-07-07 07:19 UTC, mamutmk5 commented on ansible/roles/rocketchat/templates/fixup-job.yml.j2
> +                memory: "50Mi"
Also at this point make the memory configurable and set for production and referenc the limit and request to the same value.

2023-07-07 09:06 UTC, mamutmk5 approved these changes

2023-07-10 13:52 UTC, merged