Bc 4256 integration tldraw
hpi-schul-cloud/dof_app_deploy pull request #586
Opened 2023-07-28 10:24 UTC by blazejpass

# Description

## Links to Tickets or other pull requests
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4277
https://ticketsystem.dbildungscloud.de/browse/BC-4256
https://github.com/hpi-schul-cloud/nuxt-client/pull/2691

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-08-23 13:16 UTC, bn-pass approved these changes

2023-10-12 14:26 UTC, CeEv requested changes
Please also contact devops for approve. Some parts are unclear for me.

2023-10-12 14:26 UTC, CeEv commented on ansible/group_vars/all/x_ingress.yml
> +    servicePort: "{{ PORT_TLDRAW_CLIENT }}"
To make github linter happy -> add line break.

2023-10-12 14:26 UTC, CeEv commented on ansible/group_vars/infra/pod.yml
> +TLDRAW_CLIENT_REPLICAS: 1
line break

2023-10-12 14:26 UTC, CeEv commented on ansible/group_vars/loadtest/pod.yml
> +TLDRAW_CLIENT_REPLICAS: 1
line break

2023-10-12 14:26 UTC, CeEv commented on ansible/host_vars/prod-brb/version.yml
> +TLDRAW_CLIENT_IMAGE_TAG: 1.0.0
line break at the end on nearly all all next files.

2023-10-12 14:26 UTC, CeEv commented on ansible/group_vars/infra/pod.yml
> +STORAGE_REPLICAS: 1
This confuse me. 
We have TLDRAW_EDITOR_REPLICAS and TLDRAW_EDITOR_REPLICAS in develop. 
We have a different TLDRAW_CLIENT_REPLICAS for all of the prod.yml files.

For dev you add 3, for prod only 1.

2023-11-02 16:05 UTC, Loki-Afro requested changes

2023-11-02 16:05 UTC, Loki-Afro commented on ansible/group_vars/all/config.yml
> +  TLDRAW_DB_URL:
always gets supplied via a secret

2023-11-02 16:05 UTC, Loki-Afro commented on ansible/group_vars/all/x_ingress.yml
> +  tldraw_client:
@mamutmk5 is this as it should be with the new ingress changes?

2023-11-02 16:05 UTC, Loki-Afro commented on ansible/group_vars/brb/instance_cfg.yml
> +PORT_TLDRAW: 3345
unnecessary

2023-11-02 16:05 UTC, Loki-Afro commented on ansible/group_vars/brb/instance_cfg.yml
> +PORT_TLDRAW_CLIENT: 3046
unnecessary

2023-11-02 16:05 UTC, Loki-Afro commented on ansible/group_vars/default/instance_cfg.yml
> +PORT_TLDRAW: 3345
unnecessary

2023-11-02 16:05 UTC, Loki-Afro commented on ansible/group_vars/default/instance_cfg.yml
> +PORT_TLDRAW_CLIENT: 3046
unnecessary

2023-11-02 16:19 UTC, mamutmk5 requested changes

2023-11-02 16:19 UTC, mamutmk5 commented on ansible/group_vars/all/x_ingress.yml
> +    servicePort: "{{ PORT_TLDRAW_CLIENT }}"
The Every ingress rule shoud move to the server or to the tldraw-client as an own ingress definition like https://github.com/hpi-schul-cloud/schulcloud-server/blob/main/ansible/roles/schulcloud-server-core/templates/api-files-ingress.yml.j2 as example for the Server

2023-11-02 16:19 UTC, mamutmk5 commented on ansible/group_vars/all/x_ingress.yml
> +    servicePort: "{{ PORT_TLDRAW_CLIENT }}"
the `/tldraw-client-runtime.config.json` is include at the `/tldraw` rule,
Thie are prefix rules that mean every thing what start with `/tldraw` is include at the first rulle.
Only if you want exludet things like `/tldraw-server` with an own ingress rule it will be exlude from the rule `/tldraw`

2023-11-02 16:19 UTC, mamutmk5 commented on ansible/group_vars/production/resources.yml
> +TLDRAW_CLIENT_CPU_REQUESTS: "500m"
For CPU you cann and shoud not set REQUEST to Limit.
The reqeuest can be like 100 and the limit like 4000

2023-11-02 16:19 UTC, mamutmk5 commented on ansible/host_vars/infra.dbildungscloud-01/version.yml
> +TLDRAW_CLIENT_IMAGE_TAG: 1.0.0
Ask the POs if thy thing the tldraw client shoud be at the same version as the rest of the software even it is new

2023-11-02 16:22 UTC, mamutmk5 commented on ansible/group_vars/all/x_ingress.yml
> +  tldraw_client:
@Loki-Afro thanks for the hint. I commented on the Ingress rules

2023-11-20 10:39 UTC, mamutmk5 requested changes

2023-11-20 10:39 UTC, mamutmk5 commented on ansible/group_vars/all/x_ingress.yml
> +    servicePort: "{{ PORT_TLDRAW_CLIENT }}"
Please restruct it  to the new ingress sorting, that the tldraw-clinet ingress is in the tldraw-client repo and for the tldwar-server part the ingress is at the ansible role at the server

2023-11-29 08:17 UTC, closed without merging