BC-4955 - Activate privacy policy upload on new admin page
hpi-schul-cloud/dof_app_deploy pull request #623
Opened 2023-08-31 08:56 UTC by davwas

# Description

QA note:
Change tested, no issues found. All acceptance criteria are met, but verification only by code. To be sure of the change, the change should be checked after implementation when the change is implemented from env main to env staging and env staging to env prod. see tickiet: https://ticketsystem.dbildungscloud.de/browse/BC-4955

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/BC-4955
https://github.com/hpi-schul-cloud/nuxt-client/pull/2783
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4375

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-08-31 09:10 UTC, wiaderwek requested changes

2023-08-31 09:10 UTC, wiaderwek commented on ansible/group_vars/all/config.yml
>      nuxtclient: false
isn't is used in nuxt-client also?

2023-08-31 09:10 UTC, wiaderwek commented on ansible/group_vars/nbc/instance_cfg.yml
> -FEATURE_SCHOOL_POLICY_ENABLED: "true"
we should keep it since for nbc is should be anabled for production

2023-08-31 09:13 UTC, davwas commented on ansible/group_vars/nbc/instance_cfg.yml
> -FEATURE_SCHOOL_POLICY_ENABLED: "true"
acceptance criteria say:
1. privacy policy upload is available on main branch instances.
2. privacy policy upload is NOT available on staging and prod instances (remains hidden via feature flag)
So I don't think it should be enabled for nbc just yet

2023-08-31 09:15 UTC, davwas commented on ansible/group_vars/all/config.yml
>      nuxtclient: false
nuxt client gets env vars directly from the server so I believe this part is actually irrelevant

2023-08-31 09:17 UTC, wiaderwek commented on ansible/group_vars/nbc/instance_cfg.yml
> -FEATURE_SCHOOL_POLICY_ENABLED: "true"
So, maybe contact with Magda, MArcin or Ingwert to clarify this, sice I belive that it should stay enabled on nbc.

2023-08-31 10:10 UTC, wiaderwek approved these changes

2023-08-31 10:58 UTC, virgilchiriac commented on ansible/group_vars/develop/cfg.yml
> +FEATURE_SCHOOL_POLICY_ENABLED: "true"
because we set default to true no need to have it here again
(we want to keep these ovewrite files to minimum)

2023-08-31 10:59 UTC, virgilchiriac approved these changes

2023-09-01 12:49 UTC, wiaderwek approved these changes

2023-09-01 13:09 UTC, virgilchiriac commented on ansible/group_vars/develop/cfg.yml
> +FEATURE_SCHOOL_POLICY_ENABLED_NEW: "true"
so the old policy remains enabled only on NBC prod? Is that correct?

2023-09-01 16:59 UTC, davwas commented on ansible/group_vars/develop/cfg.yml
> +FEATURE_SCHOOL_POLICY_ENABLED_NEW: "true"
correct

2023-09-07 07:43 UTC, merged