N21-1206 show classes and goups
hpi-schul-cloud/dof_app_deploy pull request #643
Opened 2023-09-15 07:28 UTC by MarvinOehlerkingCap

# Description
- add FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED
- add groups to ingress

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/N21-1206
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4406

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-09-19 14:40 UTC, IgorCapCoder approved these changes

2023-09-21 07:43 UTC, arnegns approved these changes

2023-09-21 08:08 UTC, arnegns requested changes

2023-09-21 08:08 UTC, arnegns commented on ansible/host_vars/nbc_host/cfg.yml
> +FEATURE_SHOW_NEW_CLASS_VIEW_ENABLED: "true"
Can you set this feature for the instance to true and explicit set it for ref and prod to false. Then we have a better overview which features arent activated in ref and prod

2023-09-22 07:51 UTC, arnegns approved these changes

2023-09-27 13:48 UTC, merged