BC-740 - BC-854 - ansible variable generation for docker image tag
hpi-schul-cloud/dof_app_deploy pull request #65
Opened 2021-11-23 15:55 UTC by mamutmk5

# Description
The ansible variable for the docker image tag will be generated by the git repository name and put to the host variables directory.

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/BC-854
https://ticketsystem.hpi-schul-cloud.org/browse/BC-740

## Changes
The ansible variable for the docker image tag will be generated by the git repository name and put to the host variables directory.

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2021-11-23 16:10 UTC, virgilchiriac requested changes

2021-11-23 16:10 UTC, virgilchiriac commented on .github/workflows/deploy.yml
> +          for i in ./ansible/host_vars/*; do echo "${ansible_varname}_IMAGE_TAG: $commit_id" >> $i/$filename.yml; done
this ticket is not about creating new files and folders, we should only do the rename

2021-11-23 16:33 UTC, mamutmk5 commented on .github/workflows/deploy.yml
> +          for i in ./ansible/host_vars/*; do echo "${ansible_varname}_IMAGE_TAG: $commit_id" >> $i/$filename.yml; done
yes and no, it's the renaming part :D
- an new variable was add, first part of renaming, for backwards compatibility the old variable and his place are in place
- the location where the variable is stored is renamed to a new location
- the way how the location where renamed is like the generation for the old location
- the new location is now the at an file at the host var folder for each host and not more in the main form the variables for the role 
- see for it https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence

2021-11-24 09:19 UTC, alriese commented on .github/workflows/deploy.yml
> +          for i in ./ansible/host_vars/*; do echo "${ansible_varname}_IMAGE_TAG: $commit_id" >> $i/$filename.yml; done
Thanks, the explanation and the link was very helpful.

2021-11-24 09:19 UTC, alriese approved these changes

2021-11-24 10:13 UTC, alriese commented on .github/workflows/deploy.yml
> +          for i in ./ansible/host_vars/*; do echo "${ansible_varname}_IMAGE_TAG: $commit_id" >> $i/$filename.yml; done
Maybe this is easier to read:
```suggestion
          ansible_varname=$(echo ${{ matrix.repos }} | tr [a-z] [A-Z] | tr - _ | tr \. _ | tr [:blank:] _ )
          filename=$(echo ${ansible_varname} | tr [A-Z] [a-z] )
          tennens=(brb default nbc)
          for i in "${tennens[@]}"; do
                    mkdir -pv "ansible/host_vars/${i}_host"
                    echo "${ansible_varname}_IMAGE_TAG: $commit_id" >> "./ansible/host_vars/${i}_host/${filename}.yml"
          done
```

2021-11-24 11:50 UTC, mamutmk5 commented on .github/workflows/deploy.yml
> +          for i in ./ansible/host_vars/*; do echo "${ansible_varname}_IMAGE_TAG: $commit_id" >> $i/$filename.yml; done
no and don't make that what i whant.
Especially for what i plan later on this is not so great, for one of the next steps the folder for the host at host_vars maybe go to be dynamic.
Then the docker image tag should be go to a host explizit, that's why the host folder at the host_vars folder where create. The last thing is the merging of files who are extracted form arcives are overwriting. So it's easyser and better to put the Ansible variable with the docker image tag to seperat files.

2021-11-24 12:29 UTC, virgilchiriac commented on .github/workflows/deploy.yml
> +          for i in ./ansible/host_vars/*; do echo "${ansible_varname}_IMAGE_TAG: $commit_id" >> $i/$filename.yml; done
don't understand the objection, because the suggestion does the same thing

2021-11-24 12:29 UTC, virgilchiriac approved these changes

2021-11-24 12:33 UTC, merged