BC-740 remove backwards compatibility for ansible image tag variable
hpi-schul-cloud/dof_app_deploy pull request #66
Opened 2021-11-25 08:04 UTC by alriese

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-11-25 14:03 UTC, mamutmk5 requested changes
No, thats not the right time for it to remove it.
Please lock at schulcloud-editor and edtrio who is includet at the ansible playbock https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/ansible/playbook.yml#L25-L26 .

https://github.com/hpi-schul-cloud/schulcloud-editor
https://github.com/hpi-schul-cloud/edtrio

2021-11-26 10:21 UTC, virgilchiriac commented
> No, thats not the right time for it to remove it. Please lock at schulcloud-editor and edtrio who is includet at the ansible playbock https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/ansible/playbook.yml#L25-L26 .
> 
> https://github.com/hpi-schul-cloud/schulcloud-editor https://github.com/hpi-schul-cloud/edtrio

let's change that please - even if repo is archived, it is in use (only repos not in use should be archived)

2021-11-29 09:50 UTC, virgilchiriac commented on .github/workflows/deploy.yml
> -          mkdir -pv ansible/group_vars/all
is this really not needed?

2021-11-29 15:42 UTC, alriese commented
Will be handled later

2021-11-29 15:42 UTC, closed without merging