BC-5456 - add deploy action for dev host
hpi-schul-cloud/dof_app_deploy pull request #669
Opened 2023-10-16 07:50 UTC by mamutmk5

# Description
Part 1 for split the deployment to dev for each hoast to an one job.
It allow easier to rerun the job for an dev host if the job fail.
In this PR it only add the github action file for the job and not change the deploy job for dev deployment that will be add at the next PR.

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/BC-5456

## Changes
- only add .github/workflows/deploy_dev_host.yml as file with the new dev deployment job

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-10-16 12:22 UTC, Loki-Afro requested changes

2023-10-16 12:22 UTC, Loki-Afro commented on .github/workflows/deploy_dev_host.yml
> +name: For dev host
any better name?

2023-10-16 12:48 UTC, mamutmk5 commented on .github/workflows/deploy_dev_host.yml
> +name: For dev host
What is your Suggestions for it?

2023-10-17 09:43 UTC, Loki-Afro approved these changes

2023-10-17 09:51 UTC, merged