bc-5537 namespace activator/scaled objects
hpi-schul-cloud/dof_app_deploy pull request #672
Opened 2023-10-17 17:27 UTC by Loki-Afro

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-10-19 08:05 UTC, mamutmk5 commented on sc-common/namespace-activator/app.yml
> +        imagePullPolicy: IfNotPresent
Woud prefer pin to an version or if the man image tage is used then the imagePullPolicy to always

2023-10-19 08:35 UTC, Loki-Afro commented on ansible/roles/namespace-activator-scaled-objects/defaults/main.yml
> +  - redis-deployment
nope, they are running without redis

2023-10-19 08:36 UTC, Loki-Afro commented on sc-common/namespace-activator/app.yml
> +            memory: 124Mi
actually 64Mi is fine as well..

2023-10-19 08:38 UTC, Loki-Afro commented on sc-common/namespace-activator/app.yml
> +        imagePullPolicy: IfNotPresent
i do not want to do that

2023-10-19 08:39 UTC, Loki-Afro commented on ansible/roles/namespace-activator-scaled-objects/templates/scaled-object.yml.j2
> +  cooldownPeriod: 3600
testing if keda still polls when being in that period (which it should and does)

2023-10-19 08:40 UTC, Loki-Afro commented on sc-common/namespace-activator/app.yml
> +            memory: 124Mi
suggestion assuming memory is at 64Mi?

2023-10-19 08:40 UTC, Loki-Afro commented on sc-common/namespace-activator/mongo.yml
> +            memory: 256Mi
suggestion?

2023-10-19 10:01 UTC, mamutmk5 commented on sc-common/namespace-activator/app.yml
> +            memory: 124Mi
like for memory from 64Mi to 512Mi for the dev cluster i'm an optimist :D

2023-10-19 10:02 UTC, mamutmk5 commented on sc-common/namespace-activator/mongo.yml
> +            memory: 256Mi
Dev Cluster optimist living :D 
```suggestion
        resources:
          limits:
            cpu: 4000m
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 128Mi
```

2023-10-19 10:03 UTC, mamutmk5 commented on sc-common/namespace-activator/app.yml
> +            memory: 124Mi
```suggestion
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
```

2023-10-20 10:26 UTC, mamutmk5 requested changes

2023-10-20 10:26 UTC, mamutmk5 commented on ansible/roles/ingress/templates/ingress.yml.j2
> +{% endif %}
The proxy_intercept_errors shoud only add if the namespace activator is there and not at gerneral level 
```suggestion
{% if KEDA_NAMESPACE_ACTIVATOR_ENABLED is defined %}
      proxy_intercept_errors on;
      error_page 503 = @errorpages;

      location @errorpages {
        return 302 'https://activate.cd.dbildungscloud.dev/namespace?namespace={{ NAMESPACE }}&redirected-from-503=true';
      }
{% endif %}
```

2023-10-20 10:26 UTC, mamutmk5 commented on ansible/roles/namespace-activator-scaled-objects/tasks/main.yml
> +    loop: "{{ deployments_for_scaled_objects }}"
Why the split up and don't use the scaled-object.yml.j2 directly at the apply task?
The {{ item }} is also at the template who is use in apply scaled objects there.

```suggestion
  - name: apply scaled objects
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: scaled-object.yml.j2
      apply: true
    loop: "{{ deployments_for_scaled_objects }}"
```

2023-10-20 10:26 UTC, mamutmk5 commented on ansible/roles/namespace-activator-scaled-objects/templates/keda-secret.yml.j2
> +  itemPath: "vaults/sc-dev-cd/items/keda"
```suggestion
  itemPath: "vaults/{{ ONEPASSWORD_OPERATOR_VAULT }}/items/keda"
```

2023-10-20 10:26 UTC, mamutmk5 commented on ansible/roles/ingress/templates/ingress.yml.j2
> +{% endif %}
Why not set the **_default-backend-404-svc_** as [default-backend](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#default-backend) and then if the **_default-backend-404-deployment_** is scale down an **_activator-deployment_** is scale up who is bound to the  **_default-backend-404-svc_** ?

2023-10-23 12:13 UTC, Loki-Afro commented on ansible/roles/ingress/templates/ingress.yml.j2
> +{% endif %}
because this messes too much with other deployments as well, also i'm after 503 not 404 AND default-backend in ingress works differntly then we use the default-backend service

2023-10-23 13:39 UTC, mamutmk5 requested changes

2023-10-23 13:39 UTC, mamutmk5 commented on sc-common/namespace-activator/app.yml
> +    app: api
```suggestion
    app: ns-activator
```

2023-10-23 15:18 UTC, mamutmk5 approved these changes

2023-10-23 15:59 UTC, merged