Thr 18 feature h5p editor
hpi-schul-cloud/dof_app_deploy pull request #682
Opened 2023-10-26 08:32 UTC by MajedAlaitwniCap

# Description

## Links to Tickets or other pull requests
PR schulcloud-server: https://github.com/hpi-schul-cloud/schulcloud-server/pull/4337
PR nuxt-client : https://github.com/hpi-schul-cloud/nuxt-client/pull/2748
PR: schulcloud-client: https://github.com/hpi-schul-cloud/schulcloud-client/pull/3277

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-11-06 11:10 UTC, CeEv requested changes

2023-11-06 11:10 UTC, CeEv commented on ansible/host_vars/default_host/cfg.yml
> +FEATURE_H5P_EDITOR_ENABLED: "true"
My last info is that h5p should only rollout on thr. If this is correct than it must be changed.

2023-11-06 17:13 UTC, Loki-Afro requested changes

2023-11-06 17:13 UTC, Loki-Afro commented on ansible/group_vars/all/config.yml
> +    value: "https://h5p.org/"
there is still no solution for that one ..

2023-11-07 08:12 UTC, casparneumann-cap commented on ansible/group_vars/all/config.yml
> +    value: "https://h5p.org/"
This will be solved in correspondence with Hannes Hensel via implementing a proxy.

2023-11-13 08:31 UTC, CeEv approved these changes

2023-11-13 08:31 UTC, CeEv commented on ansible/group_vars/all/config.yml
> +    value: "https://h5p.org/"
The proxy is already implemented, or a open task with existing ticket?

2023-11-13 08:42 UTC, casparneumann-cap commented on ansible/group_vars/all/config.yml
> +    value: "https://h5p.org/"
Der Proxy wird aktuell vom SRE Team bearbeitet. Hauptansprechpartner hierzu sind Lars Dahlke & Dimitrij Pinneker

2023-11-15 15:16 UTC, mamutmk5 reviewed
Befor it go to main the ingress definitions must addet to the new ingress conzept.
It's mean that the ingress definiton for h5p-staticfiles-server must go to the ansible role and files at https://github.com/hpi-schul-cloud/h5p-staticfiles-server
Not more https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/ansible/host_vars/default_host/x_ingress.yml
https://github.com/hpi-schul-cloud/dof_app_deploy/blob/main/ansible/group_vars/all/x_ingress.yml#L98-L107

2023-11-16 12:43 UTC, Loki-Afro approved these changes
not approving for myself but entwicklungsleitung

2023-11-16 13:17 UTC, merged