N21-1336  FEATURE_COMPUTE_TOOL_STATUS_WITHOUT_VERSIONS_ENABLED
hpi-schul-cloud/dof_app_deploy pull request #697
Opened 2023-11-08 13:28 UTC by IgorCapCoder

add feature flag and set it to true for dev-nbc only.

# Description

## Links to Tickets or other pull requests
- https://ticketsystem.dbildungscloud.de/browse/N21-1336
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4534

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-11-08 16:13 UTC, Loki-Afro commented
very descriptive

2023-11-10 14:48 UTC, MarvinOehlerkingCap requested changes

2023-11-10 14:48 UTC, MarvinOehlerkingCap commented on ansible/group_vars/reference/cfg.yml
> +FEATURE_COMPUTE_TOOL_STATUS_WITHOUT_VERSIONS_ENABLED: "false"
why is it enabled on dev and prod but disabled on ref? just set the feature to true in the config.yml

2023-11-14 08:39 UTC, IgorCapCoder commented on ansible/group_vars/reference/cfg.yml
> +FEATURE_COMPUTE_TOOL_STATUS_WITHOUT_VERSIONS_ENABLED: "false"
fixed :)

2023-11-14 08:44 UTC, IgorCapCoder commented
> very descriptive

Added words ;)

2023-11-14 09:24 UTC, MarvinOehlerkingCap approved these changes

2023-11-14 11:37 UTC, merged