BC-5522 - add var for the admin server port
hpi-schul-cloud/dof_app_deploy pull request #702
Opened 2023-11-15 12:29 UTC by bn-pass

# Description

## Links to Tickets or other pull requests

https://ticketsystem.dbildungscloud.de/browse/BC-5522

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-11-16 22:02 UTC, WojciechGrancow approved these changes

2023-11-27 10:48 UTC, mamutmk5 requested changes

2023-11-27 10:48 UTC, mamutmk5 commented on ansible/group_vars/brb/instance_cfg.yml
> +PORT_ADMIN_SERVER: 4030
Where is it used if no where then delet it

2023-11-29 11:10 UTC, sszafGCA commented on ansible/group_vars/brb/instance_cfg.yml
> +PORT_ADMIN_SERVER: 4030
I think it can be deleted

2023-11-29 15:40 UTC, mamutmk5 requested changes

2023-11-30 08:20 UTC, sszafGCA commented on ansible/host_vars/ref-audit/pod.yml
> +ADMIN_API_SERVER_REPLICAS: 3
done

2023-11-30 08:21 UTC, sszafGCA commented on ansible/host_vars/ref-nbc/pod.yml
> +ADMIN_API_SERVER_REPLICAS: 3
done

2023-11-30 08:26 UTC, mamutmk5 approved these changes

2023-11-30 09:20 UTC, mamutmk5 approved these changes

2023-11-30 11:23 UTC, merged