BC-3844 - Vue3 upgrade with Webpack and Jest
hpi-schul-cloud/dof_app_deploy pull request #775
Opened 2024-02-02 11:57 UTC by MartinSchuhmacher

# Description
To be able to use the latest features of Vue we want to upgrade the frontend to Vue 3. Despite many projects using Vite and Vitest with Vue3 it is still possible to stick to Webpack and Jest. Because the transition to new building and testing libraries (Vite and Vitest) would create a lot of effort we want to try to do upgrade to Vue 3 keeping the existing libraries.

## Links to Tickets or other pull requests
BC-3844
BC-6337

## Changes
- deactivate migration page

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-02-02 14:11 UTC, uidp approved these changes

2024-02-02 14:11 UTC, uidp commented on ansible/group_vars/nbc/instance_cfg.yml
> -FEATURE_SHOW_MIGRATION_WIZARD: "true"
Is it okay to remove these lines? Should we maybe comment them?

2024-02-02 14:22 UTC, MartinSchuhmacher commented
FYI: this branch will be merged once the corresponding update branch from Vue3 is merged

2024-02-13 15:58 UTC, Loki-Afro commented
@MartinSchuhmacher why did you need to remove those migration ids?

2024-02-13 16:31 UTC, MartinSchuhmacher commented
> @MartinSchuhmacher why did you need to remove those migration ids?

as it was commented out on the other config I thought it was simply forgotten during the process, if its needed on this instance, just suggest to remove my commenting and I will have a look next wednesday when I'm back from my vacation

2024-02-27 10:20 UTC, mamutmk5 reviewed
Please remove lines that are no longer used and do not comment them out

2024-02-27 10:20 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> -  FEATURE_COURSE_SHARE_NEW:
Where is the corosponding operation who remove the feature flag `FEATURE_COURSE_SHARE_NEW`  from Server and nuxt-client?

https://github.com/hpi-schul-cloud/nuxt-client/blob/main/src/store/types/env-config.ts

2024-02-27 10:20 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
>      value: "true"
Why is the default for the feature flage `FEATURE_COURSE_SHARE` change from false to true?

2024-02-27 10:30 UTC, MarvinOehlerkingCap requested changes

2024-02-27 10:30 UTC, MarvinOehlerkingCap commented on ansible/group_vars/nbc/instance_cfg.yml
> +#FEATURE_ENABLE_LDAP_SYNC_DURING_MIGRATION: "true"
this is a feature that has to be enabled

2024-02-27 10:30 UTC, MarvinOehlerkingCap commented on ansible/group_vars/nbc/instance_cfg.yml
> +#FEATURE_SHOW_MIGRATION_WIZARD: "true"
This feature is in use and will be released soon in lower saxony and should not be disabled.
FEATURE_SHOW_MIGRATION_WIZARD, FEATURE_USER_MIGRATION_ENABLED and FEATURE_USER_MIGRATION_SYSTEM_ID have to be configured!

2024-02-27 10:30 UTC, MarvinOehlerkingCap commented on ansible/host_vars/prod-nbc/cfg.yml
> +#FEATURE_SHOW_MIGRATION_WIZARD: "false"
The feature has to be overwritten here, since the feature is not released yet, but will in the next sprint.

2024-02-27 10:30 UTC, MarvinOehlerkingCap commented on ansible/host_vars/ref-nbc/cfg.yml
> +#FEATURE_SHOW_MIGRATION_WIZARD: "false"
The feature has to be overwritten here, since the feature is not released yet, but will in the next sprint.

2024-02-27 10:30 UTC, MarvinOehlerkingCap commented on ansible/host_vars/nbc_host/cfg.yml
> +# FEATURE_USER_MIGRATION_SYSTEM_ID: "0000d186816abba584714c93"
The system id has to be configured for the migration wizard to work

2024-02-27 10:33 UTC, MartinSchuhmacher commented on ansible/group_vars/all/config.yml
> -  FEATURE_COURSE_SHARE_NEW:
@odalys-dataport added that to the PR, seems it is covered by this one https://github.com/hpi-schul-cloud/nuxt-client/pull/2789/files#diff-9b9479116225db5cbf75d12f17a73f066adc33eab22df68d94dea94a8fc2371bL13

not sure about the server part though

2024-02-27 10:41 UTC, MartinSchuhmacher commented on ansible/group_vars/all/config.yml
>      value: "true"
not sure either, but according to https://github.com/hpi-schul-cloud/dof_app_deploy/pull/405/files#diff-9b72c401b6f650e6aae80587e229f60db10ca2d09a3128f108a584156131a812L456 that seems correct

2024-02-27 10:44 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
>      value: "true"
A okay you move the feature flag `FEATURE_COURSE_SHARE_NEW` to `FEATURE_COURSE_SHARE` at view, then the question is is there anything at the sever repo what must be done?

2024-02-27 10:49 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
>      value: "true"
Okay there is code for the new and the old feature flag at the server repo.

https://github.com/search?q=repo%3Ahpi-schul-cloud%2Fschulcloud-server+FEATURE_COURSE_SHARE&type=code

2024-02-27 10:53 UTC, MartinSchuhmacher commented on ansible/group_vars/all/config.yml
>      value: "true"
I checked, that there was an old server PR but the changes are not merged and the PR was just closed, I will ask within my team why that is

2024-02-27 11:13 UTC, MartinSchuhmacher commented on ansible/group_vars/all/config.yml
>      value: "true"
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4775

2024-02-27 11:45 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
>      value: "true"
Hat not in mind that the old one is also used at the legacy-client to activate the old course copy.
I don't find the PR for removing it there 

https://github.com/search?q=repo%3Ahpi-schul-cloud%2Fschulcloud-client%20FEATURE_COURSE_SHARE&type=code

2024-02-27 12:31 UTC, MarvinOehlerkingCap approved these changes

2024-02-27 13:58 UTC, MartinSchuhmacher commented on ansible/group_vars/all/config.yml
>      value: "true"
deacitvated for now in legacy client, will create follow up for that to remove it in legacy client

2024-02-27 14:50 UTC, merged