BC-6119-Activate creation of tldraw and deactivate creation of neXboa…
hpi-schul-cloud/dof_app_deploy pull request #776
Opened 2024-02-05 08:38 UTC by VikDavydiuk

…rds on STG and PROD

# Description

## Links to Tickets or other pull requests

- https://ticketsystem.dbildungscloud.de/browse/BC-6119

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-02-05 14:39 UTC, Loki-Afro commented on ansible/group_vars/production/cfg.yml
> +FEATURE_NEXBOARD_COPY_ENABLED: "false"
are you sure about that?
nexboard is still enabled for prod everywhere but nbc

2024-02-05 14:46 UTC, Loki-Afro approved these changes

2024-02-06 16:22 UTC, bn-pass approved these changes

2024-03-11 11:09 UTC, blazejpass approved these changes

2024-03-11 11:17 UTC, mamutmk5 requested changes
Missig the activation of the TLDRAW service deployments for all Instances `WITH_TLDRAW: true` 
Also missing the adjustments of the numbers of the pods for prod like i did at #809

2024-03-11 11:29 UTC, mamutmk5 approved these changes

2024-03-11 11:38 UTC, merged