BC-1330 Move config endpoint
hpi-schul-cloud/dof_app_deploy pull request #795
Opened 2024-02-19 08:22 UTC by CeEv

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-02-21 08:56 UTC, mamutmk5 requested changes

2024-02-21 08:56 UTC, mamutmk5 commented on ansible/group_vars/all/x_ingress.yml
>      servicePort: "{{ PORT_SERVER }}"
Only remove the old route the /api/v3 route is open by the api-ingress at the server repo
https://github.com/hpi-schul-cloud/schulcloud-server/blob/main/ansible/roles/schulcloud-server-core/templates/ingress.yml.j2

2024-02-21 11:40 UTC, CeEv commented on ansible/group_vars/all/x_ingress.yml
>      servicePort: "{{ PORT_SERVER }}"
Ok, die v3 Routen sind generell offen. Dann entferne ich die beiden.

2024-02-21 12:24 UTC, mamutmk5 approved these changes

2024-02-26 14:26 UTC, closed without merging

2024-02-26 14:26 UTC, CeEv commented
Move to BC-6676.