BC-6676 - Use v3 config
hpi-schul-cloud/dof_app_deploy pull request #815
Opened 2024-03-15 10:34 UTC by bischofmax

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-03-20 10:11 UTC, SevenWaysDP approved these changes

2024-03-22 08:12 UTC, SevenWaysDP approved these changes

2024-03-25 07:14 UTC, CeEv requested changes

2024-03-25 07:14 UTC, CeEv commented on ansible/group_vars/all/config.yml
> +  I18N__DEFAULT_LANGUAGE:
Die Änderungen in all/config.yml sind unnötig. Das sind die default Werte die auch in default.schema.json stehen. 
Solange keine Abweichung existiert tragen wir sie hier nicht ein.

2024-03-25 12:05 UTC, CeEv approved these changes

2024-03-26 09:28 UTC, merged