Feature/bc 999 update status pages
hpi-schul-cloud/dof_app_deploy pull request #82
Opened 2022-01-05 11:23 UTC by MartinSchuhmacher

# Description

As a user, I want to be directed to the new status page when I click the link "Status" in the footer.

## Links to Tickets or other pull requests

Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/BC-999
Client-PR: https://github.com/hpi-schul-cloud/schulcloud-client/pull/2739 
Nuxt-PR: https://github.com/hpi-schul-cloud/nuxt-client/pull/2013
Dev-PR: 

## Changes

- environment variable set to default (dBildungscloud) and individually set for each instance

## Data Security <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

ALERT_STATUS_URL: https://status.INSTANCE.de

## New Repos, NPM packages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] QA: In addition to review, the code has been manually tested (if manual testing is possible)
- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definition of Done
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2022-01-06 13:36 UTC, Metauriel commented on ansible/group_vars/brb/instance_cfg.yml
> +ALERT_STATUS_URL: https://status.brandenburg.cloud
does it make sense to link to the production status page here?
Maybe ask Paul about it

2022-01-07 12:53 UTC, MartinSchuhmacher commented on ansible/group_vars/brb/instance_cfg.yml
> +ALERT_STATUS_URL: https://status.brandenburg.cloud
will change that after talking to Ralf

2022-01-10 07:40 UTC, mamutmk5 requested changes
- Please put the joined variable for ALERT_STATUS_URL to https://github.com/hpi-schul-cloud/dof_app_deploy/tree/feature/BC-999-update-status-pages/ansible/group_vars/develop/instance_develop_cfg.yml it's need only to set one time.
- Please add for the referenc Invoiorment for dbildungscloud the ALERT_STATUS_URL to  https://github.com/hpi-schul-cloud/dof_app_deploy/blob/feature/BC-999-update-status-pages/ansible/host_vars/ref-dbildungscloud/cfg.yml
- Please add for the referenc Invoiorment for Brandenburg the ALERT_STATUS_URL to  https://github.com/hpi-schul-cloud/dof_app_deploy/blob/feature/BC-999-update-status-pages/ansible/host_vars/ref-brb/cfg.yml
- Please add for the referenc Invoiorment for Niedersachsen the ALERT_STATUS_URL to  
https://github.com/hpi-schul-cloud/dof_app_deploy/blob/feature/BC-999-update-status-pages/ansible/host_vars/ref-nbc/cfg.yml
- Please add for the referenc Invoiorment for International the ALERT_STATUS_URL to  
https://github.com/hpi-schul-cloud/dof_app_deploy/blob/feature/BC-999-update-status-pages/ansible/host_vars/ref-int/cfg.yml
- Please add for the referenc Invoiorment for Thüringen the ALERT_STATUS_URL to  
https://github.com/hpi-schul-cloud/dof_app_deploy/blob/feature/BC-999-update-status-pages/ansible/host_vars/ref-thr/cfg.yml

2022-01-10 14:34 UTC, Loki-Afro approved these changes

2022-01-10 14:45 UTC, mamutmk5 approved these changes

2022-01-10 14:53 UTC, merged