BC-7024-migration-to-ionos-postgres-dev
hpi-schul-cloud/dof_app_deploy pull request #834
Opened 2024-04-05 13:26 UTC by YannickEvers

# Description
Switch to IONOS Postgres Cluster for the dev stage. Automatically create and delete branch- and application-specific databases and users for calendar, hydra and erwinidm.

- Split `WITH_DATABASES` into `WITH_MONGO_DATABASES` and `WITH_POSTGRES_DATABASES` to control them individually
- Disable `WITH_POSTGRES_DATABASES` and activate new `WITH_BRANCH_POSTGRES_DB_MANAGEMENT`
- Role creates Secrets for the database cluster (from 1Password) and the three application databases (branch as prefix)
- Role creates the users and database in a Kubernetes Job
- Role prepares a suspended job for deleting the databases and users
- Add parts that conditionally (`WITH_BRANCH_POSTGRES_DB_MANAGEMENT`) overwrite the database config/credentials for erwinidm, calendar (see PR TBD) and hydra
- Add steps to the Github `clean_workflow` for triggering the suspended job and waiting for it's completion (=deletion)

## Links to Tickets or other pull requests
[OPS-6241](https://ticketsystem.dbildungscloud.de/browse/OPS-6241)

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-04-09 08:27 UTC, mamutmk5 reviewed
it's a great idea but, the looping part for the ansible task it's not so great and it's also violating the part that at least the creating of thing should be in the ansible role where it's needed.
For example the creating and initzialising of the Postgres DB for the calendar shoud be in the calendar ansible role.

2024-04-09 09:41 UTC, YannickEvers commented
> it's a great idea but, the looping part for the ansible task it's not so great and it's also violating the part that at least the creating of thing should be in the ansible role where it's needed. For example the creating and initzialising of the Postgres DB for the calendar shoud be in the calendar ansible role.

Putting that part in each role would result in many redundancies. The role is more of a replacement for dof_postgres, which previously created the database deployment needed for the applications (and a schema specific for erwinidm). The specific initialization parts are still in the roles.
For the other stages the database creation is part of the infra-schulcloud deployment.

2024-04-12 07:53 UTC, YannickEvers commented on .github/workflows/clean.yml
> +    uses: hpi-schul-cloud/dof_app_deploy/.github/workflows/clean_workflow.yml@BC-7024-migration-to-ionos-postgres-dev
Reminder to revert this before merging.

2024-04-15 09:35 UTC, Loki-Afro commented on ansible/roles/dof_postgresql_management/tasks/main.yml
> +  when: db_secret_present.resources|length == 0
does that really work if the operator is not fast enough?

2024-04-22 07:44 UTC, YannickEvers commented on ansible/roles/dof_postgresql_management/tasks/main.yml
> +  when: db_secret_present.resources|length == 0
You probably mean the onepassword-operator, right? The secret checked here is not managed by it. There are two separate secrets: One coming from 1Password with the credentials for the whole Postgres cluster and one with the branch/database specific credentials that is created directly with a random password.

2024-04-23 08:15 UTC, mamutmk5 requested changes

2024-04-23 08:15 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/postgres_management/job-database-init.yml.j2
> +metadata:
Missing the labes.
```suggestion
metadata:
  labels:
    app: pg-{{ database_name }}-init
    app.kubernetes.io/part-of: schulcloud-verbund
    app.kubernetes.io/name: pg-{{ database_name }}-init
    app.kubernetes.io/component: idm
    app.kubernetes.io/managed-by: ansible
    git.repo: {{ DOF_APP_DEPLOY_REPO_NAME }}
```

2024-04-23 08:15 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/postgres_management/job-database-init.yml.j2
> +        app: postgres
missig labels
```suggestion
      labels:
        app: postgres
        app: pg-{{ database_name }}-init
        app.kubernetes.io/part-of: schulcloud-verbund
        app.kubernetes.io/name: pg-{{ database_name }}-init
        app.kubernetes.io/component: idm
        app.kubernetes.io/managed-by: ansible
        git.repo: {{ DOF_APP_DEPLOY_REPO_NAME }}
```

2024-04-23 08:15 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/postgres_management/job-database-init.yml.j2
> +        - name:  psql-config
name the container properly like `erwinidm-pg-init` or so

2024-04-23 08:15 UTC, mamutmk5 commented on .github/workflows/clean_workflow.yml
> +            kubectl --kubeconfig=files/config_$CLUSTER --namespace $branch_identifier patch job/pg-deletion-job -p '{"spec":{"suspend":false}}' || echo "::warning::Couldn't clean up the postgres data
The postgress deletion job(s) don't work as you thing it will only delete one db.
The configmaps from each job and the jobs selfe over write eatch other in the end only one job and only one configmap will be there and only on DB and user are deleted

2024-04-23 08:15 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/postgres_management/job-database-deletion.yml.j2
> +  name: pg-deletion-job
Missing a proper name and the labels for this job

2024-04-23 08:15 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/postgres_management/onepassword-pg-cluster.yml.j2
Will be over written by the other same files.
For example ansible/roles/hydra/templates/postgres_management/onepassword-pg-cluster.yml.j2

2024-04-23 09:28 UTC, YannickEvers commented on ansible/roles/erwin-idm/templates/postgres_management/job-database-init.yml.j2
> +  name: pg-{{ database_name }}-init-job-{{ 1000000 | random | hash('md5') }}
Discussed: Job runs every time (indempotent). This way the previous job is still visible for some time. It will be automatically deleted later (ttlSecondsAfterFinished). Reducing the time to 30 minutes to reduce the list of jobs.

2024-04-23 12:46 UTC, YannickEvers commented on ansible/roles/erwin-idm/templates/postgres_management/job-database-init.yml.j2
> +metadata:
Labels added.

2024-04-23 12:46 UTC, YannickEvers commented on ansible/roles/erwin-idm/templates/postgres_management/job-database-init.yml.j2
> +        app: postgres
Labels added.

2024-04-23 12:48 UTC, YannickEvers commented on ansible/roles/erwin-idm/templates/postgres_management/job-database-init.yml.j2
> +        - name:  psql-config
Done (for hydra and calendar as well).

2024-04-23 13:47 UTC, mamutmk5 requested changes

2024-04-23 13:47 UTC, mamutmk5 commented on ansible/group_vars/infra/with.yml
> +WITH_MONGO_DATABASES: true
missing if `WITH_POSTGRES_DATABASES` or `WITH_BRANCH_POSTGRES_DB_MANAGEMENT`

2024-04-23 13:47 UTC, mamutmk5 commented on ansible/group_vars/loadtest/with.yml
> +WITH_MONGO_DATABASES: true
missing if `WITH_POSTGRES_DATABASES` or `WITH_BRANCH_POSTGRES_DB_MANAGEMENT`

2024-04-24 06:58 UTC, YannickEvers commented on ansible/group_vars/loadtest/with.yml
> +WITH_MONGO_DATABASES: true
The plan is to have both false here as well (like infra). But we don't have a Postgres Cluster there yet ([OPS-6256](https://ticketsystem.dbildungscloud.de/browse/OPS-6256)). So in this case we should keep WITH_POSTGRES_DATABASES for now, you are right.

2024-04-25 14:59 UTC, merged