N21 1823 add other group users feature flag
hpi-schul-cloud/dof_app_deploy pull request #845
Opened 2024-04-16 06:09 UTC by mrikallab

# Description
This PR will introduce a new feature flag for activation and deactivation of other group users provisioning.

## Links to Tickets or other pull requests
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4930
https://ticketsystem.dbildungscloud.de/browse/N21-1823

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-04-16 14:54 UTC, IgorCapCoder approved these changes

2024-04-17 08:43 UTC, MarvinOehlerkingCap requested changes

2024-04-17 08:43 UTC, MarvinOehlerkingCap commented on ansible/group_vars/all/config.yml
> +  FEATURE_OTHER_GROUPUSERS_PROVISIONING_ENABLED:
`FEATURE_SCHULCONNEX_OTHER_GROUPUSERS_PROVISIONING_ENABLED`, to be more in line with `FEATURE_SCHULCONNEX_COURSE_SYNC_ENABLED`

2024-04-17 08:43 UTC, MarvinOehlerkingCap commented on ansible/group_vars/all/config.yml
> +    value: false
has to be `value: "false"`

2024-04-17 08:43 UTC, MarvinOehlerkingCap commented on ansible/group_vars/all/config.yml
> +    value: false
and should be true in every environment

2024-04-17 09:10 UTC, mrikallab commented on ansible/group_vars/all/config.yml
> +    value: false
Why should be true in every environment ? There is no use of it currently in nuxt or old client..

2024-04-17 11:30 UTC, MarvinOehlerkingCap commented on ansible/group_vars/all/config.yml
> +    value: false
environment meaning dev, ref, prod

2024-04-18 06:52 UTC, MarvinOehlerkingCap approved these changes

2024-04-19 09:35 UTC, merged