BC-6770 - Create a list board
hpi-schul-cloud/dof_app_deploy pull request #846
Opened 2024-04-16 09:54 UTC by MartinSchuhmacher

# Description
Distribute env var for list board correctly

## Links to Tickets or other pull requests
BC-6770
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4914
https://github.com/hpi-schul-cloud/nuxt-client/pull/3199

## Changes
- adding `FEATURE_BOARD_LAYOUT_ENABLED`

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-04-18 07:55 UTC, virgilchiriac approved these changes

2024-04-18 12:19 UTC, odalys-dataport requested changes

2024-04-18 12:19 UTC, odalys-dataport commented on ansible/group_vars/all/config.yml
> +  FEATURE_BOARD_LAYOUT_ENABLED:
I find this name a bit confusing tbh, why didn't we choose `FEATURE_BOARD_LIST_TYPE_ENABLED` or anything more explicit like that?

2024-04-18 13:52 UTC, odalys-dataport commented on ansible/group_vars/all/config.yml
> +  FEATURE_BOARD_LAYOUT_ENABLED:
I see, I mean I don't have a strong opinion on this tbh, since this feature flag is gonna be removed after release anyways, right?

2024-04-19 07:27 UTC, MartinSchuhmacher commented on ansible/group_vars/all/config.yml
> +  FEATURE_BOARD_LAYOUT_ENABLED:
exactly :)

2024-04-22 07:55 UTC, merged