BC-7101 - collaboration service deployment
hpi-schul-cloud/dof_app_deploy pull request #859
Opened 2024-05-06 11:18 UTC by hoeppner-dataport

# Description
Implement a deployment for the BoardCollaboration-WebSocket-Server.

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-05-06 11:53 UTC, Metauriel commented on ansible/group_vars/develop/cfg.yml
> +BOARD_COLLABORATION_SERVER_REPLICAS: 3
that wont work until we have done the ticket for scaling...

2024-05-06 13:03 UTC, hoeppner-dataport commented on ansible/group_vars/develop/cfg.yml
> +BOARD_COLLABORATION_SERVER_REPLICAS: 3
Changed to one replica

2024-05-06 13:03 UTC, Metauriel approved these changes

2024-05-06 14:57 UTC, mamutmk5 requested changes

2024-05-06 14:57 UTC, mamutmk5 commented on ansible/group_vars/develop/cfg.yml
> +BOARD_COLLABORATION_URI: "ws://localhost:4450"
If this works, then the websocet will be bound on the pod to the pod and not for any remote system or via the deployment, please chack this and myebe use {{ DOMAIN }} instant as host and no port.

2024-05-06 14:57 UTC, mamutmk5 commented on ansible/group_vars/all/config.yml
> +    value: ""
Only add an default value if you want to set them to an default value who is not empty and "" is to see as empty
mabey set the websocet to the domain is an good idee
```suggestion
    value: "ws://{{ DOMAIN }}"
```

2024-05-07 12:25 UTC, mamutmk5 approved these changes

2024-05-07 13:26 UTC, hoeppner-dataport commented on ansible/group_vars/develop/cfg.yml
> +BOARD_COLLABORATION_URI: "ws://localhost:4450"
removed the whole setting

2024-05-07 13:26 UTC, hoeppner-dataport commented on ansible/group_vars/all/config.yml
> +    value: ""
fixed as suggested

2024-05-07 14:57 UTC, merged