BC-7467 - Cleanup etherpad env vars
hpi-schul-cloud/dof_app_deploy pull request #883
Opened 2024-06-07 07:24 UTC by bischofmax

# Description

## Links to Tickets or other pull requests
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5057
- https://ticketsystem.dbildungscloud.de/browse/BC-7467

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-06-11 08:19 UTC, mamutmk5 approved these changes

2024-06-11 08:57 UTC, bergatco approved these changes

2024-06-12 08:22 UTC, mamutmk5 requested changes
The Changes at this point are not compare to the changes at the config at the server repo and if you rename things please do it with tow PRs in one Sprint or inform all Teams that they must update they server branches with main after the merge of the server pr otherwise you break there dev deployments

2024-06-12 11:08 UTC, bergatco approved these changes

2024-06-12 12:44 UTC, mamutmk5 approved these changes

2024-06-13 12:56 UTC, bergatco approved these changes

2024-06-13 13:21 UTC, merged