EW-965 Update erwin-idm image tag
hpi-schul-cloud/dof_app_deploy pull request #899
Opened 2024-07-05 11:12 UTC by SimoneRadtke-Cap

# Description
Update the erwin-idm image tag to 0.4.8 for upgrading Keycloak to version 25.

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/EW-965

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-07-05 11:14 UTC, mkreuzkam-cap approved these changes

2024-07-09 08:10 UTC, mamutmk5 requested changes

2024-07-09 08:10 UTC, mamutmk5 commented on ansible/group_vars/all/instance_config_all.yml
> +IDENTITY_MANAGEMENT__URI: "https://idm-{{ DOMAIN }}"
Don't do it in this way. It will not work for all instances and at the moment the managment thing is not public at the ingress. So let the old wan please or other wise alter the ingress to the right things.

2024-07-09 08:10 UTC, mamutmk5 commented on ansible/group_vars/all/erwin-idm.yml
> +ERWINIDM_MANAGEMENT_PORT: 8090
Please add this also to the deployment and service also we don't want to have prots configurable any more so code it hard where you use it.

2024-07-10 08:22 UTC, psachmann commented on ansible/group_vars/all/erwin-idm.yml
> +ERWINIDM_MANAGEMENT_PORT: 8090
Done.

2024-07-11 11:18 UTC, mamutmk5 requested changes
Miss

2024-07-11 11:18 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/deployment.yml.j2
Missing at the Port Section of the depliyment the KC_HTTP_MANAGMENT_PORT to be set.
For example the port 8089 at https://github.com/hpi-schul-cloud/dof_app_deploy/blob/EW-965/ansible/roles/erwin-idm/templates/deployment.yml.j2#L50-L52

2024-07-11 11:18 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/configmap.yml.j2
> +  KC_HTTP_MANAGEMENT_PORT: "8090"
Missing the add of the Prot 8090 to the kubernetes Service or is this port only for the pod?
https://github.com/hpi-schul-cloud/dof_app_deploy/blob/EW-965/ansible/roles/erwin-idm/templates/svc.yml.j2

2024-07-11 12:02 UTC, mkreuzkam-cap commented on ansible/roles/erwin-idm/templates/configmap.yml.j2
> +  KC_HTTP_MANAGEMENT_PORT: "8090"
The port 8090 is only needed for the health probes and management functions and should not be exposed. (this split of the ports is a new security feature in keycloak)

2024-07-11 12:24 UTC, mamutmk5 commented on ansible/roles/erwin-idm/templates/configmap.yml.j2
> +  KC_HTTP_MANAGEMENT_PORT: "8090"
There is a difference between Public exposing via Ingress and add the Port to the POD definition from the deployment and to the service.
The port definition at the POD template from the deployment helps to understand what port's the pod have. It don't allow or prevent other PODs and things in the cluster to connect to the pod. For example the health prob from Kubernetes go via network to the pod.
If the Port is defined at a service it makes it easy to use from other pods at the cluster.
Also it depends on the kubernets service type. In this case it’s clusterIP and it’s only an Loadbalanced IP at the k8s cluster where other PODs can connect against to this port.

2024-07-11 13:52 UTC, mamutmk5 approved these changes

2024-07-12 12:28 UTC, Fshmit approved these changes

2024-07-15 06:41 UTC, merged