Ew 838
hpi-schul-cloud/dof_app_deploy pull request #904
Opened 2024-07-15 13:18 UTC by psachmann

# Description
TBA

## Links to Tickets or other pull requests
- https://ticketsystem.dbildungscloud.de/browse/EW-837

## Changes

## Deployment
TBA

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-07-15 14:56 UTC, mamutmk5 requested changes

2024-07-15 14:56 UTC, mamutmk5 commented on ansible/playbook_rollout.yml
> +      when: WITH_COMMON_CARTRIDGE is defined and WITH_COMMON_CARTRIDGE|bool
It's not necessary to check the when condition as is also at add as conditions for the job in the ansible role
```suggestion
    - role: common-cartridge
```
And put it after the `schulcloud-client-core` role and bevore the `post_deployment` role. 
The `post_deployment` ansible role shoud be the last role, it marks that the deployment is finished

2024-07-24 07:41 UTC, psachmann commented on ansible/playbook_rollout.yml
> +      when: WITH_COMMON_CARTRIDGE is defined and WITH_COMMON_CARTRIDGE|bool
Done

2024-07-24 07:41 UTC, psachmann commented on ansible/playbook.yml
> +    - common-cartridge
Done

2024-07-24 12:00 UTC, mamutmk5 commented
Importen for Merging this PR you must first merge hpi-schul-cloud/schulcloud-server#5078 so that the ansible role is there then add the ansible role add to the playbocks works with out an error as the playbock is rolled out to dev

2024-07-24 12:49 UTC, mamutmk5 approved these changes

2024-08-01 09:34 UTC, merged