BC-7793-ionos-mongodb
hpi-schul-cloud/dof_app_deploy pull request #938
Opened 2024-08-19 13:09 UTC by YannickEvers

# Description
Part of the migration to IONOS MongoDB.
Adds role for ExternalSecrets configuration for the creation of the SecretStore of the namespace with a token with the necessary permissions.
Namespaces are now labeled with their DB prefixes (used for cleanup).
MongoDB Cleanup CronJob added to sc-common: Checks if there are DBs that don't start with a prefix of the existing Namespaces in the K8S Cluster and removes them.

Implements a branch specific Secret (DB name in connection String is different for each namespace) via ExternalSecrets for:
- etherpad-secret
- mongodb-query-exporter-secret
- rocketchat-secret

Should be merged after it's counterpart in schulcloud-server and the data migration for the main branch is done.

## Links to Tickets or other pull requests
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5191
[OPS-6706](https://ticketsystem.dbildungscloud.de/browse/OPS-6706)
[BC-7793](https://ticketsystem.dbildungscloud.de/browse/BC-7793)

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-08-27 14:24 UTC, mamutmk5 requested changes

2024-08-27 14:24 UTC, mamutmk5 commented on ansible/roles/dof_mongo_management/tasks/main.yml
Ansible Label missing for the Ansible task

2024-08-27 14:24 UTC, mamutmk5 commented on ansible/roles/external-secrets/templates/secret-token.yml.j2
> +    token: "{{ secretstore_token.resources[0].data.token }}"
Cann you explayn where the valuie for `secretstore_token.resources[0].data.token` came from?

2024-08-27 14:24 UTC, mamutmk5 commented on ansible/roles/external-secrets/tasks/main.yml
Ansible Tags are missing for the ansible task in this file

2024-08-27 14:30 UTC, mamutmk5 requested changes
Miss the line to remove `ExternalSecret` at the `delete_namespaces` job in the 
 github action`.github/workflows/clean_workflow.yml`

2024-08-28 07:26 UTC, YannickEvers commented on ansible/roles/dof_mongo_management/tasks/main.yml
Ah, I overlooked the two roles. Added now.

2024-08-28 07:27 UTC, YannickEvers commented on ansible/roles/external-secrets/tasks/main.yml
Added now. I used 1password as tag for all tasks here, because they are secret related.

2024-08-28 07:37 UTC, YannickEvers commented on ansible/roles/external-secrets/templates/secret-token.yml.j2
> +    token: "{{ secretstore_token.resources[0].data.token }}"
We read the Secret for the ServiceAccount Token in the task before (register) and then save it here in a secret in the branch namespace. I will change the code a bit to make that clearer.

2024-08-28 12:44 UTC, mamutmk5 commented on ansible/roles/external-secrets/templates/secret-token.yml.j2
> +    token: "{{ secretstore_token.resources[0].data.token }}"
Sound link an hack for using this ServiceAccount Token in an other Item.
Normaly the Service Account Token is use from an POD who is Bound to an ServiceAccount to Speak with the Kube API.

2024-08-29 08:07 UTC, YannickEvers commented on ansible/roles/external-secrets/templates/secretstore.yml.j2
> +            key: token
I tried that, but it seems to only accepts a ServiceAccounts in the same namespace.

2024-08-30 07:51 UTC, mamutmk5 approved these changes

2024-09-19 08:35 UTC, simoncolincap commented on sc-common/db-cleanup/base/cronjob-database-cleanup.yml
> +  schedule: "* * * * *"
Does this need to run every minute? I think it's fine if it runs once a day or maybe once every hour

2024-09-19 08:52 UTC, mamutmk5 commented on sc-common/db-cleanup/base/cronjob-database-cleanup.yml
> +  schedule: "* * * * *"
No, every minute is that what we want.
It's importen to delete the Databases very short after the namespaces are deleted so the developers have the change to rebuild there namespace and databeses from scretsh if thy want

2024-09-19 10:59 UTC, simoncolincap commented on sc-common/db-cleanup/base/cronjob-database-cleanup.yml
> +  schedule: "* * * * *"
Ok that makes sense

2024-09-19 11:00 UTC, simoncolincap approved these changes

2024-09-20 06:52 UTC, merged