Ops 6751 h5p tests
hpi-schul-cloud/dof_app_deploy pull request #956
Opened 2024-09-02 08:36 UTC by dimapin

2024-09-02 13:40 UTC, YannickEvers commented on ansible/group_vars/reference/clammit.yml
> +WITH_CLAMMIT: true
I think we have to define a defaults in group_vars/all as well, otherwise the `if WITH_CLAMMIT` conditions will fail on e.g. infra/production.

2024-09-02 13:45 UTC, YannickEvers commented on ansible/playbook.yml
> +    - clammit
If it should be rolled out on reference the role has to be added to playbook_rollout.yml as well.

2024-09-02 14:07 UTC, YannickEvers commented on ansible/roles/h5p-proxy/templates/api-h5p-proxy-configmap-files.yml.j2
> +      location /api/v3/h5p-editor/ajax {
We added options for `max_body_size` and timeouts for `location /api/v3/h5p-editor` to make bigger file uploads possible. Do we need them here as well or does the clammit proxy behave in a way that makes them unnecessary?
And this part probably should be added only if `WITH_CLAMMIT` is true, right?

2024-09-03 06:41 UTC, simoncolincap commented on ansible/roles/clammit/tasks/main.yml
> +      state: "{{ 'present' if WITH_CLAMMIT else 'absent'}}"
This can cause errors if there are undefined variables in the templates

2024-09-03 19:42 UTC, dimapin commented on ansible/group_vars/reference/clammit.yml
> +WITH_CLAMMIT: true
fixed

2024-09-03 19:42 UTC, dimapin commented on ansible/roles/clammit/tasks/main.yml
> +      state: "{{ 'present' if WITH_CLAMMIT else 'absent'}}"
fixed

2024-09-04 15:16 UTC, YannickEvers approved these changes

2024-09-06 14:35 UTC, mamutmk5 requested changes

2024-09-09 06:39 UTC, dimapin commented on ansible/roles/clammit/tasks/main.yml
> +      state: "{{ 'present' if WITH_CLAMMIT is defined and WITH_CLAMMIT|bool else 'absent'}}"
Good hint

2024-09-09 07:46 UTC, mamutmk5 approved these changes

2024-09-09 07:52 UTC, merged